mod dca;
mod trade_flow;

include!("lib_parts/part_000.rs");
include!("lib_parts/part_001.rs");
include!("lib_parts/part_002.rs");
include!("lib_parts/part_003.rs");
include!("lib_parts/part_004.rs");
include!("lib_parts/part_005.rs");
include!("lib_parts/part_006.rs");
include!("lib_parts/part_007.rs");
include!("lib_parts/part_008.rs");
include!("lib_parts/part_009.rs");
include!("lib_parts/part_010.rs");
include!("lib_parts/part_011.rs");
include!("lib_parts/part_012.rs");
include!("trade_flow/cycle_window_timers.rs");
include!("trade_flow/ws_fast_path.rs");
include!("trade_flow/overlap_audit.rs");
include!("lib_parts/part_013.rs");
include!("trade_flow/triggers/market_price_events.rs");
include!("trade_flow/triggers/market_price.rs");
include!("lib_parts/part_015.rs");
include!("lib_parts/part_016.rs");
include!("lib_parts/part_017.rs");
include!("lib_parts/part_018.rs");
include!("lib_parts/part_019.rs");
include!("lib_parts/part_020.rs");
include!("lib_parts/part_021.rs");
include!("lib_parts/part_022.rs");
include!("trade_builder/exit_math.rs");
include!("trade_builder/runtime_price.rs");
include!("trade_builder/fill_resolution.rs");
include!("trade_builder/exit_retry.rs");
include!("trade_builder/notification.rs");
include!("trade_builder/guard_waiting.rs");
include!("trade_builder/exit_sibling_priority.rs");
include!("trade_builder/order_expiry.rs");
include!("trade_builder/trigger_sizes.rs");
include!("trade_builder/order_submit.rs");
include!("trade_builder/cancel_reconcile.rs");
include!("trade_builder/open_order_reconcile.rs");
include!("trade_builder/fill_finalize.rs");
include!("trade_builder/price_resolution.rs");
include!("trade_builder/armed_ws_eval.rs");
include!("trade_builder/tick_trigger_eval.rs");
include!("trade_builder/order_processing.rs");
include!("lib_parts/part_027.rs");
include!("lib_parts/part_028.rs");

#[cfg(test)]
mod tests;
