import type { NodeFieldSchema } from './types';
import { PTB_MODE_OPTIONS } from './ptb-modes';

export const ACTION_PLACE_ORDER_FIELD_SCHEMA: NodeFieldSchema[] = [
    { key: 'sourceTradeId', label: 'Source Trade ID', input: 'number' },
    {
      key: 'mode',
      label: 'Mod',
      input: 'select',
      options: [
        { label: 'single', value: 'single' },
        { label: 'pair_lock', value: 'pair_lock' },
      ],
      help: 'single mevcut tek-bacak davranisidir. pair_lock ayni node icinde karsi bacagi da yonetir.',
    },
    {
      key: 'side',
      label: 'Yön',
      input: 'select',
      options: [
        { label: 'buy', value: 'buy' },
        { label: 'sell', value: 'sell' },
      ],
    },
    {
      key: 'executionMode',
      label: 'Islem Modu',
      input: 'select',
      options: [
        { label: 'market (IOC)', value: 'market' },
        { label: 'limit (GTC)', value: 'limit' },
      ],
      help: 'market secimi piyasa benzeri davranis icin IOC + agresif fiyat kullanir.',
    },
    { key: 'marketSlug', label: 'Market Slug', input: 'text' },
    { key: 'tokenId', label: 'Token ID', input: 'text' },
    { key: 'outcomeLabel', label: 'Outcome Label', input: 'text' },
    {
      key: 'sizeMode',
      label: 'Tutar Modu',
      input: 'select',
      options: [
        { label: 'USDC', value: 'usdc' },
        { label: 'Shares', value: 'shares' },
        { label: '% (Pozisyon Yüzdesi)', value: 'pct' },
      ],
      help: "shares sabit adet, pct Source Trade notional'ının yüzdesi olarak hesaplanır.",
    },
    { key: 'sizeUsdc', label: 'Tutar (USDC)', input: 'number' },
    { key: 'targetQty', label: 'Target Qty', input: 'number' },
    { key: 'sizePct', label: 'Tutar (%)', input: 'number', help: 'Geçerli aralık: 0 < % <= 100.' },
    {
      key: 'buyFillLockEnabled',
      label: 'Paylasimli Buy Fill Lock',
      input: 'checkbox',
      help: 'Ayni `buyFillLockGroup` icindeki baska bir buy node ayni market cycle icinde fill aldiysa bu node yeni buy acmaz.',
    },
    {
      key: 'buyFillLockGroup',
      label: 'Buy Fill Lock Grubu',
      input: 'text',
      help: 'Birden fazla buy node ayni grup adini kullanirsa ortak fill lock paylasir.',
    },
    {
      key: 'releaseBuyFillLockOnStopLoss',
      label: 'Tam Stop-Loss Sonrasi Lock Ac',
      input: 'checkbox',
      help: 'Aktifken lock sahibi pozisyon klasik SL veya PTB SL ile tamamen kapandiginda ayni grup yeniden entry alabilir.',
    },
    { key: 'minPriceDistanceCent', label: 'Minimum Fiyat Mesafesi (cent)', input: 'number' },
    { key: 'maxTriggers', label: 'Maksimum Tetikleme', input: 'number' },
    {
      key: 'kind',
      label: 'Emir Tipi',
      input: 'select',
      options: [
        { label: 'immediate', value: 'immediate' },
        { label: 'conditional', value: 'conditional' },
      ],
    },
    {
      key: 'triggerCondition',
      label: 'Tetik Koşulu',
      input: 'select',
      options: [
        { label: 'Yok', value: '' },
        { label: 'cross_above', value: 'cross_above' },
        { label: 'cross_below', value: 'cross_below' },
        { label: 'level_above', value: 'level_above' },
        { label: 'level_below', value: 'level_below' },
      ],
    },
    { key: 'triggerPrice', label: 'Tetik Fiyatı', input: 'number', help: 'cross_* icin gecis seviyesi, level_* icin durum eşiği olarak kullanılır.' },
    { key: 'expiresAt', label: 'Bitiş Zamanı', input: 'datetime-local' },
    {
      key: 'tpEnabled',
      label: 'Take Profit',
      input: 'select',
      options: [
        { label: 'Kapali', value: 'false' },
        { label: 'Aktif', value: 'true' },
      ],
      help: 'Buy emri doldurulunca TP child sell acmaya izin verir. TP Fiyat alani hard full-close TP icin, kademe satirlari ise staged partial TP icin kullanilir; ikisi ayni anda aktif olabilir.',
    },
    { key: 'tpPriceCent', label: 'TP Fiyat (cent)', input: 'number', help: 'Hard full-close TP seviyesi. Tetiklenirse o andaki kalan pozisyonun tamami kapanir; staged TP satirlariyla birlikte kullanilabilir.' },
    {
      key: 'slEnabled',
      label: 'Stop Loss',
      input: 'select',
      options: [
        { label: 'Kapali', value: 'false' },
        { label: 'Aktif', value: 'true' },
      ],
      help: 'Buy emri doldurulunca SL child sell acmaya izin verir. Pair lock modunda bu alan ana bacagi kontrol eder. SL Fiyat alani hard full-close SL icin, kademe satirlari ise staged partial SL icin kullanilir; ikisi ayni anda aktif olabilir.',
    },
    {
      key: 'ptbStopLossEnabled',
      label: 'PTB Gap Stop-Loss',
      input: 'checkbox',
      help: 'Underlying Chainlink/PTB directional gap belirtilen esige indiginde ek bir hard full-close PTB stop-loss child sell orderi olusturur. Bu alan karsi outcome token fiyatini degil, PTB referansina gore directional gap\'i izler. Pair lock modunda bu alan ana bacagi kontrol eder.',
    },
    { key: 'slPriceCent', label: 'SL Fiyat (cent)', input: 'number', help: 'Hard full-close SL seviyesi. Tetiklenirse o andaki kalan pozisyonun tamami kapanir; staged SL satirlariyla birlikte kullanilabilir.' },
    {
      key: 'ptbStopLossGapUsd',
      label: 'PTB Gap Esiği',
      input: 'number',
      help: 'Secili birime gore directional gap esigi. Up/Yes icin current Chainlink - PTB, Down/No icin PTB - current Chainlink kullanilir; negatif deger karsi yone overshoot bekler.',
    },
    {
      key: 'ptbStopLossGapUnit',
      label: 'PTB Gap Birimi',
      input: 'select',
      options: [
        { label: 'USD', value: 'usd' },
        { label: 'Cent', value: 'cent' },
      ],
      help: 'Cent modunda 1 = $0.01. Bu birim hard gap ve staged PTB satirlarinin tamamina uygulanir.',
    },
    {
      key: 'ptbStopLossTimeDecayMode',
      label: 'PTB SL Zaman Modu',
      input: 'select',
      options: [
        { label: 'tighten', value: 'tighten' },
        { label: 'relax', value: 'relax' },
        { label: 'none', value: 'none' },
      ],
      help: 'tighten: pencere sonuna yaklastikca pozitif PTB gap kuculur. relax: buyur. none: sabit kalir. Negatif gaplerde decay uygulanmaz.',
    },
    {
      key: 'slTriggerPriceMode',
      label: 'SL Tetik Fiyat Modu',
      input: 'select',
      options: [
        { label: 'Best Bid', value: 'best_bid' },
        { label: 'Composite (Legacy)', value: 'composite' },
        { label: 'Composite Safe', value: 'composite_safe' },
        { label: 'Composite Fast', value: 'composite_fast' },
        { label: 'Last Trade', value: 'last_trade' },
      ],
      help: 'Best Bid: en konservatif. Composite (Legacy): mevcut eski composite davranisi. Composite Safe: divergence + best bid onayi ile daha gec tetikler. Composite Fast: min(best_bid,last_trade) ile daha hizli tetikler. Last Trade: sadece son islemi kullanir.',
    },
    {
      key: 'reenterOnSlHit',
      label: 'SL Sonrasi Re-entry',
      input: 'checkbox',
      help: 'Yalniz upstream trigger.market_price repeatMode=once arkasindaki immediate buy node icin gecerli. SL ladder aktifse tum SL kademeleri icin ortak re-entry davranisini kontrol eder.',
    },
    {
      key: 'stagedSlReentryOnlyAfterAllStages',
      label: 'Tum SL Kademeleri Sonrasi Re-entry',
      input: 'checkbox',
      help: 'Aktifken staged SL veya staged PTB re-entry ancak tum stop-loss kademeleri tamamlandiginda tek sefer schedule edilir.',
    },
    {
      key: 'reentryMaxAttempts',
      label: 'Re-entry Deneme Limiti',
      input: 'number',
      help: 'SL sonrasi maksimum yeniden alis deneme sayisi. Gecerli aralik: 1-10.',
    },
    {
      key: 'reentryCooldownSec',
      label: 'Re-entry Cooldown (sn)',
      input: 'number',
      help: 'SL sonrasi trigger.market_price yeniden schedule edilmeden once beklenecek minimum sure.',
    },
    {
      key: 'reentrySkipCurrentWindow',
      label: 'Ayni Pencereyi Atla',
      input: 'checkbox',
      help: 'Aktifken re-entry mevcut market penceresinde tekrar denenmez; bir sonraki pencere beklenir.',
    },
    {
      key: 'reentryMinPriceCent',
      label: 'Re-entry Min Fiyat (cent)',
      input: 'number',
      help: 'Yalniz re-entry denemelerinde uygulanir. Current price bu seviyenin altindaysa mevcut trigger guard semantigiyle bloklar.',
    },
    {
      key: 'reentryMaxPriceCent',
      label: 'Re-entry Max Fiyat (cent)',
      input: 'number',
      help: 'Yalniz re-entry denemelerinde uygulanir. Best ask / desired reference bu seviyeyi asarsa mevcut max price guard semantigiyle bloklar.',
    },
    {
      key: 'reentryPriceToBeatMaxDiff',
      label: 'Re-entry PTB Min Fark',
      input: 'number',
      help: 'Yalniz SL sonrasi re-entry denemelerinde kullanilir. Ana PTB manual ise ayni birimi miras alir; ana PTB auto ise asagidaki override birimi ile manual threshold olarak uygulanir.',
    },
    {
      key: 'reentryPriceToBeatMaxDiffUnit',
      label: 'Re-entry PTB Birimi',
      input: 'select',
      options: [
        { label: 'USD', value: 'usd' },
        { label: 'Cent', value: 'cent' },
      ],
      help: 'Yalniz ana PTB modu auto iken gerekir. Re-entry override degerinin USD mi cent mi oldugunu belirler.',
    },
    {
      key: 'reentryThresholdDecay',
      label: 'Re-entry PTB Decay',
      input: 'number',
      help: 'Generation arttikca re-entry PTB override veya manual base threshold bu carpan kadar daralir. Ornek: 0.8',
    },
    {
      key: 'reentryMaxPriceTightenBps',
      label: 'Re-entry MaxPrice Tighten (bps)',
      input: 'number',
      help: 'Generation arttikca effective maxPrice bu basis point orani kadar sikilasir. Ornek: 500 = %5',
    },
    {
      key: 'maxPriceCent',
      label: 'Tavan Fiyat (cent)',
      input: 'number',
      help: 'Bu fiyatin ustunde buy emri gonderme. Bossa node ici tavan snapshot yoktur; upstream tetik gecerli bir maxPrice tasiyorsa editor onu otomatik doldurabilir.',
    },
    {
      key: 'triggerPriceGuardEnabled',
      label: 'Tetik Fiyat Korumasi',
      input: 'checkbox',
      help: 'Runtime current_price upstream tetik fiyatinin altina dusulurse buy emrini engelle.',
    },
    {
      key: 'retryOnTriggerPriceGuardBlock',
      label: 'Tetik Fiyat Bekle',
      input: 'checkbox',
      help: 'Trigger guard orderi iptal etmek yerine beklemeye alir; kosullar duzelince yeniden dener.',
    },
    {
      key: 'executionFloorGuardEnabled',
      label: 'Execution Floor Korumasi',
      input: 'checkbox',
      help: 'Best ask effective floor seviyesinin altindaysa buy emrini engelle. `Execution Floor Fiyat (cent)` bossa upstream tetik fiyati fallback olarak kullanilir.',
    },
    {
      key: 'executionFloorPriceCent',
      label: 'Execution Floor Fiyat (cent)',
      input: 'number',
      help: 'Opsiyonel floor override. Doluysa best ask bu seviyenin altina indiginde guard bloklar; bossa upstream tetik fiyati kullanilir.',
    },
    {
      key: 'retryOnExecutionFloorGuardBlock',
      label: 'Execution Floor Bekle',
      input: 'checkbox',
      help: 'Below-floor durumunda execution floor guard orderi iptal etmek yerine beklemeye alir; missing best ask mevcut runtime semantigini korur.',
    },
    {
      key: 'priceToBeatGuardEnabled',
      label: 'Price to Beat Korumasi',
      input: 'checkbox',
      help: 'Price to Beat ile ayni Polymarket/Chainlink current price feedini kullanir. Fark belirlenen minimum seviyenin altindaysa buy emrini engeller.',
    },
    {
      key: 'priceToBeatMode',
      label: 'PTB Modu',
      input: 'select',
      options: PTB_MODE_OPTIONS,
      help: 'Manual modda minimum fark elle girilir. Auto modlarda tamamlanmis market excursion, volatility yuzdesi, signal formula veya IV mismatch edge kullanilir.',
    },
    {
      key: 'priceToBeatMaxDiff',
      label: 'Minimum Fark',
      input: 'number',
      help: 'Fark bu degerin altindaysa emir engellenir. USD secersen 5 = $5.00, cent secersen 1 = $0.01.',
    },
    {
      key: 'priceToBeatMaxDiffUnit',
      label: 'Fark Birimi',
      input: 'select',
      options: [
        { label: 'USD', value: 'usd' },
        { label: 'Cent', value: 'cent' },
      ],
      help: 'USD veya cent sec. Cent modu 0.01 gibi decimal cent degerleri de destekler.',
    },
    {
      key: 'priceToBeatIvStalePenaltyMs',
      label: 'IV Stale Esik (ms)',
      input: 'number',
      help: 'IV mismatch edge modunda Chainlink verisi bu ms ustundeyse gap strength esigine stale ceza eklenir.',
    },
    {
      key: 'priceToBeatIvStaleGapStrengthPenalty',
      label: 'IV Stale Gap Cezasi',
      input: 'number',
      help: 'Ornek: 0.10 girersen stale durumda minGapStrength 0.10 artar.',
    },
    {
      key: 'priceToBeatIvNegativeVelocityGapStrengthPenalty',
      label: 'IV Ters Momentum Cezasi',
      input: 'number',
      help: 'Gap secilen yon aleyhine daraliyorsa minGapStrength uzerine eklenir.',
    },
    {
      key: 'priceToBeatIvBinanceMissingAskThresholdCent',
      label: 'IV Binance Eksik Ask Esigi',
      input: 'number',
      help: 'Ask bu cent seviyesinde veya ustundeyken Binance verisi yoksa ekstra edge cezasi uygulanir.',
    },
    {
      key: 'priceToBeatIvBinanceMissingPenalty',
      label: 'IV Binance Eksik Cezasi',
      input: 'number',
      help: 'Binance unavailable/stale durumunda dynamic edge threshold uzerine eklenir.',
    },
    {
      key: 'priceToBeatIvMinAdjustedMargin',
      label: 'IV Min Adj Margin',
      input: 'number',
      help: 'Edge adjusted dynamic threshold uzerine bu kadar ek marj birakmazsa trade bloklanir.',
    },
    {
      key: 'priceToBeatIvMinFinalQ',
      label: 'IV Min Final Q',
      input: 'number',
      help: 'Binance conservative-min sonrasi q_final bu seviyenin altindaysa trade bloklanir.',
    },
    {
      key: 'priceToBeatIvBinanceDisagreementThreshold',
      label: 'IV Binance Ayrisma Esigi',
      input: 'number',
      help: 'q_chain_adj Binance q uzerine bu kadar cikarsa disagreement cezasi uygulanir.',
    },
    {
      key: 'priceToBeatIvBinanceDisagreementPenalty',
      label: 'IV Binance Ayrisma Cezasi',
      input: 'number',
      help: 'Binance ayrisma esigi gecildiginde dynamic edge threshold uzerine eklenir.',
    },
    {
      key: 'priceToBeatIvLargeBinanceDisagreementThreshold',
      label: 'IV Buyuk Binance Ayrisma Esigi',
      input: 'number',
      help: 'Daha buyuk Chainlink/Binance q ayrismasinda large ceza uygulanir.',
    },
    {
      key: 'priceToBeatIvLargeBinanceDisagreementPenalty',
      label: 'IV Buyuk Binance Ayrisma Cezasi',
      input: 'number',
      help: 'Buyuk Binance ayrismasinda dynamic edge threshold uzerine eklenir.',
    },
    {
      key: 'priceToBeatIvProtectionMode',
      label: 'IV Koruma Modu',
      input: 'select',
      options: [
        { label: 'Off', value: 'off' },
        { label: 'Soft', value: 'soft' },
        { label: 'Hard', value: 'hard' },
        { label: 'Adaptive', value: 'adaptive' },
      ],
      help: 'Soft risklerde ceza ekler; hard bloklar; adaptive saatlik hacme gore rejim secerek blok/ceza/gevseme uygular.',
    },
    {
      key: 'priceToBeatIvBookLeadGuardEnabled',
      label: 'IV Book Lead Koruma',
      input: 'checkbox',
      help: 'Orderbook secilen yonun tersini guclu fiyatliyorsa protection risk uretir.',
    },
    {
      key: 'priceToBeatIvBookLeadUnderSec',
      label: 'IV Book Lead Sn',
      input: 'number',
      help: 'Book lead korumasi bu kalan saniye ve altinda uygulanir.',
    },
    {
      key: 'priceToBeatIvBookLeadMinMidDiff',
      label: 'IV Book Mid Farki',
      input: 'number',
      help: 'Up/Down mid farki bu seviyeyi asarsa book lead yonu secilir.',
    },
    {
      key: 'priceToBeatIvOppositeMidBlockCent',
      label: 'IV Ters Mid Block Cent',
      input: 'number',
      help: 'Ters taraf mid fiyati bu cent seviyesine ulasirsa protection risk uretir.',
    },
    {
      key: 'priceToBeatIvBlockOnOppositeBookLead',
      label: 'IV Ters Book Block',
      input: 'checkbox',
      help: 'Hard modda ters book lead dogrudan trade bloklar.',
    },
    {
      key: 'priceToBeatIvTooGoodToBeTrueGap',
      label: 'IV Model-Book Hard Gap',
      input: 'number',
      help: 'Legacy hard gap. Yeni configte priceToBeatIvModelBookGapHard ile ayni anlamdadir.',
    },
    {
      key: 'priceToBeatIvModelBookGapWarn',
      label: 'IV Model-Book Warn Gap',
      input: 'number',
      help: 'q_final ile secilen mid farki bu seviyeyi asarsa threshold/gap cezalari eklenir.',
    },
    {
      key: 'priceToBeatIvModelBookGapHard',
      label: 'IV Model-Book Hard Gap',
      input: 'number',
      help: 'q_final ile secilen mid farki bu seviyeyi asarsa trade hard block olur.',
    },
    {
      key: 'priceToBeatIvModelBookWarnThresholdPenalty',
      label: 'IV Model-Book Edge Ceza',
      input: 'number',
      help: 'Warning zone icin dynamic edge threshold cezası.',
    },
    {
      key: 'priceToBeatIvModelBookWarnGapPenalty',
      label: 'IV Model-Book Gap Ceza',
      input: 'number',
      help: 'Warning zone icin required gap strength cezası.',
    },
    {
      key: 'priceToBeatIvDepthGuardEnabled',
      label: 'IV Depth Koruma',
      input: 'checkbox',
      help: 'Secilen token ask ladder VWAP maliyeti best ask uzerinden kontrol edilir.',
    },
    {
      key: 'priceToBeatIvDepthMaxSlippage',
      label: 'IV Depth Max Slippage',
      input: 'number',
      help: 'VWAP avg fill ile best ask arasindaki izin verilen maksimum fark.',
    },
    {
      key: 'priceToBeatIvLateHighPriceSoftUnderSec',
      label: 'IV Late High Price Sn',
      input: 'number',
      help: 'Bu kalan saniye ve altinda pahali giris once soft ceza alir.',
    },
    {
      key: 'priceToBeatIvLateHighPriceAskCent',
      label: 'IV Late Ask Cent',
      input: 'number',
      help: 'Late high-price risk icin selected ask cent esigi.',
    },
    {
      key: 'priceToBeatIvLateHighPriceSelectedMidSoftCent',
      label: 'IV Late Soft Mid Cent',
      input: 'number',
      help: 'Selected mid bu cent altindaysa soft ceza uygulanir.',
    },
    {
      key: 'priceToBeatIvLateHighPriceThresholdPenalty',
      label: 'IV Late Edge Ceza',
      input: 'number',
      help: 'Late high-price soft zone icin threshold cezası.',
    },
    {
      key: 'priceToBeatIvLateHighPriceSelectedMidHardCent',
      label: 'IV Late Hard Mid Cent',
      input: 'number',
      help: 'Selected mid bu cent altinda ve gap zayifsa hard block olur.',
    },
    {
      key: 'priceToBeatIvLateHighPriceMinGapUsd',
      label: 'IV Late Min Gap USD',
      input: 'number',
      help: 'Late hard block icin directional gap bu USD degerinin altinda olmalidir.',
    },
    {
      key: 'priceToBeatIvParticipationAfterMinutes',
      label: 'IV Participation Min',
      input: 'number',
      help: 'Bu dakika fillsiz kalinca threshold credit uygulanir.',
    },
    {
      key: 'priceToBeatIvParticipationLongAfterMinutes',
      label: 'IV Participation Long Min',
      input: 'number',
      help: 'Bu dakika fillsiz kalinca uzun credit uygulanir.',
    },
    {
      key: 'priceToBeatIvParticipationCredit',
      label: 'IV Participation Credit',
      input: 'number',
      help: 'Kisa fillsiz sure icin threshold indirimi.',
    },
    {
      key: 'priceToBeatIvParticipationLongCredit',
      label: 'IV Participation Long Credit',
      input: 'number',
      help: 'Uzun fillsiz sure icin threshold indirimi.',
    },
    {
      key: 'priceToBeatIvParticipationMinThreshold',
      label: 'IV Participation Floor',
      input: 'number',
      help: 'Participation credit sonrasi minimum effective threshold.',
    },
    {
      key: 'priceToBeatIvParticipationCreditEnabled',
      label: 'IV Participation Credit',
      input: 'checkbox',
      help: 'Flow uzun sure fill almadiysa hard bloklari bypass etmeden thresholdu gevsetir.',
    },
    {
      key: 'priceToBeatIvRequireBinanceFreshUnderSec',
      label: 'IV Binance Zorunlu Sn',
      input: 'number',
      help: 'Bu kalan saniye ve altinda fresh Binance verisi zorunlu olur.',
    },
    {
      key: 'priceToBeatIvBinanceMaxStaleMs',
      label: 'IV Binance Max Stale Ms',
      input: 'number',
      help: 'Binance verisi bu ms uzerindeyse stale sayilir.',
    },
    {
      key: 'priceToBeatIvRequireBinanceSameDirection',
      label: 'IV Binance Yon Onayi',
      input: 'checkbox',
      help: 'Fresh Binance fiyatinin secilen PTB yonuyle ayni tarafta olmasini ister.',
    },
    {
      key: 'priceToBeatIvMomentumProtectionEnabled',
      label: 'IV Momentum Koruma',
      input: 'checkbox',
      help: 'Gap erirken drop_z esigi asilirsa protection risk uretir.',
    },
    {
      key: 'priceToBeatIvDropZBlockThreshold',
      label: 'IV Drop Z Koruma',
      input: 'number',
      help: 'Momentum korumasinin kullandigi drop_z esigi.',
    },
    {
      key: 'priceToBeatIvProtectionSoftThresholdPenalty',
      label: 'IV Soft Threshold Cezasi',
      input: 'number',
      help: 'Soft moddaki her protection riski icin dynamic threshold uzerine eklenir.',
    },
    {
      key: 'priceToBeatIvProtectionSoftGapStrengthPenalty',
      label: 'IV Soft Gap Cezasi',
      input: 'number',
      help: 'Soft moddaki her protection riski icin min gap strength uzerine eklenir.',
    },
    {
      key: 'priceToBeatIvVolumeBaselineMode',
      label: 'IV Volume Baseline',
      input: 'select',
      options: [
        { label: 'Off', value: 'off' },
        { label: 'Hourly', value: 'hourly' },
      ],
      help: 'Adaptive modda hacmi asset+saat+kalan sure bucket medyanina gore normalize eder.',
    },
    {
      key: 'priceToBeatIvVolumeBaselineLookbackDays',
      label: 'IV Volume Lookback Gun',
      input: 'number',
      help: 'Saatlik hacim baseline medyani icin geriye bakilacak gun sayisi.',
    },
    {
      key: 'priceToBeatIvVolumeWindowSec',
      label: 'IV Volume Window Sn',
      input: 'number',
      help: 'Current volume ve baseline ornekleri icin notional toplama penceresi.',
    },
    {
      key: 'priceToBeatIvVolumeBaselineMinSamples',
      label: 'IV Volume Min Sample',
      input: 'number',
      help: 'Baseline kullanmak icin gereken minimum ornek sayisi; altinda neutral davranir.',
    },
    {
      key: 'priceToBeatIvLowHourlyVolumeRatio',
      label: 'IV Low Volume Ratio',
      input: 'number',
      help: 'Bu oran alti dusuk hacim kabul edilir.',
    },
    {
      key: 'priceToBeatIvHighHourlyVolumeRatio',
      label: 'IV High Volume Ratio',
      input: 'number',
      help: 'Bu oran ustu yuksek hacim kabul edilir.',
    },
    {
      key: 'priceToBeatIvExtremeHourlyVolumeRatio',
      label: 'IV Extreme Volume Ratio',
      input: 'number',
      help: 'Bu oran ustu ekstrem hacim kabul edilir.',
    },
    {
      key: 'priceToBeatIvBookReliabilityThreshold',
      label: 'IV Book Reliability',
      input: 'number',
      help: 'Spread score * volume score bu esigi asarsa book daha guvenilir sayilir.',
    },
    {
      key: 'priceToBeatIvAdaptiveGreenEdgeDelta',
      label: 'IV Green Edge Delta',
      input: 'number',
      help: 'GREEN rejimde dynamic edge threshold uzerine uygulanacak delta.',
    },
    {
      key: 'priceToBeatIvAdaptiveGreenGapStrengthDelta',
      label: 'IV Green Gap Delta',
      input: 'number',
      help: 'GREEN rejimde min gap strength uzerine uygulanacak delta.',
    },
    {
      key: 'priceToBeatIvAdaptiveOrangeEdgeDelta',
      label: 'IV Orange Edge Delta',
      input: 'number',
      help: 'ORANGE rejimde dynamic edge threshold uzerine uygulanacak delta.',
    },
    {
      key: 'priceToBeatIvAdaptiveOrangeGapStrengthDelta',
      label: 'IV Orange Gap Delta',
      input: 'number',
      help: 'ORANGE rejimde min gap strength uzerine uygulanacak delta.',
    },
    {
      key: 'priceToBeatIvAdaptiveOrangeGapUsdMarginDelta',
      label: 'IV Orange USD Margin Delta',
      input: 'number',
      help: 'ORANGE rejimde min gap USD margin uzerine uygulanacak delta.',
    },
    {
      key: 'priceToBeatIvAdaptiveRedBlock',
      label: 'IV Adaptive Red Block',
      input: 'checkbox',
      help: 'RED rejimde trade dogrudan bloklanir.',
    },
    {
      key: 'priceToBeatStopLossBumpEnabled',
      label: 'Auto/Manual PTB Ayari',
      input: 'checkbox',
      help: 'Manual modda SL sonrasi minimum farki artirir. Auto modda 5 miss market sonra maxPrice bazli PTB gevsemesinde tampon olarak kullanilir.',
    },
    {
      key: 'priceToBeatStopLossBumpAmount',
      label: 'PTB Tampon / Kademe',
      input: 'number',
      help: 'Manual modda her SL marketinden sonra eklenir. Auto modda gevseme hedefi icin tampon olur. Cent secersen 10 = $0.10.',
    },
    {
      key: 'priceToBeatStopLossBumpDecayWindows',
      label: 'PTB Bump Decay Pencere',
      input: 'number',
      help: 'Bu kadar problemsiz scope penceresi gecerse bump bir kademe azaltilir.',
    },
    {
      key: 'priceToBeatStopLossBumpScope',
      label: 'PTB Bump Scope',
      input: 'select',
      options: [
        { label: 'per_scope', value: 'per_scope' },
        { label: 'global', value: 'global' },
      ],
      help: 'per_scope: asset+timeframe+yon bazli. global: node geneli tek sayaç.',
    },
    {
      key: 'priceToBeatStopLossBumpMaxValue',
      label: 'PTB Max Limit',
      input: 'number',
      help: 'Yalniz manual bump icin toplam kümülatif artis bu degeri gecmez. Bossa limit yoktur.',
    },
    {
      key: 'priceToBeatStopLossBumpUnit',
      label: 'PTB Tampon Birimi',
      input: 'select',
      options: [
        { label: 'USD', value: 'usd' },
        { label: 'Cent', value: 'cent' },
      ],
      help: 'Artis miktarinin USD mi cent mi oldugunu belirler.',
    },
    {
      key: 'priceToBeatMaxPriceRelaxEnabled',
      label: 'Max Price Relax',
      input: 'checkbox',
      help: 'PTB maxPrice relax hesaplamasini bu node icin acar/kapatir.',
    },
    {
      key: 'priceToBeatMaxPriceRelaxMissCount',
      label: 'Relax Miss Sayisi',
      input: 'number',
      help: 'Art arda buy fill gelmeyen kac completed marketten sonra relax devreye girecek.',
    },
    {
      key: 'priceToBeatMaxPriceRelaxHistoryCount',
      label: 'Relax History Sayisi',
      input: 'number',
      help: 'Relax hesabi icin gecmiste kac completed market taranacak.',
    },
    {
      key: 'priceToBeatMaxPriceRelaxMinValue',
      label: 'Relax Min Deger',
      input: 'number',
      help: 'Final PTB relax sonrasi bunun altina inmez. Bossa tampon fallback kullanilir.',
    },
    {
      key: 'priceToBeatMaxPriceRelaxMinDepthUsd',
      label: 'Relax Min Depth (USDC)',
      input: 'number',
      help: 'Historical saniyede best ask maxPrice altinda olsa bile ancak depth bu USDC esigini geciyorsa tradeable sayilir.',
    },
    {
      key: 'priceToBeatMaxPriceRelaxMinUnit',
      label: 'Relax Min Birimi',
      input: 'select',
      options: [
        { label: 'USD', value: 'usd' },
        { label: 'Cent', value: 'cent' },
      ],
      help: 'Relax min degerinin USD mi cent mi oldugunu belirler.',
    },
    {
      key: 'priceToBeatMaxPriceRelaxStepMode',
      label: 'Relax Step Modu',
      input: 'select',
      options: [
        { label: 'Percent', value: 'percent' },
        { label: 'Absolute', value: 'absolute' },
      ],
      help: 'Percent modunda her ekstra miss mevcut PTB-target farkinin yuzdesi kadar, absolute modda sabit USD/cent kadar ek gevsetir.',
    },
    {
      key: 'priceToBeatMaxPriceRelaxStepValue',
      label: 'Relax Step Degeri',
      input: 'number',
      help: 'Percent modunda 25 = her ekstra miss farkin %25i. Absolute modda USD/cent cinsinden sabit adim.',
    },
    {
      key: 'priceToBeatMaxPriceRelaxStepUnit',
      label: 'Relax Step Birimi',
      input: 'select',
      options: [{ label: 'USD', value: 'usd' }, { label: 'Cent', value: 'cent' }],
      help: 'Sadece absolute modda kullanilir.',
    },
    {
      key: 'notifyOnPriceToBeatGapBlocked',
      label: 'Price to Beat Engel Bildirimi',
      input: 'checkbox',
      help: 'Price to Beat guard emri engelleyince Telegram bildirimi gonder.',
    },
    {
      key: 'retryOnPriceToBeatGuardBlock',
      label: 'Price to Beat Bekle',
      input: 'checkbox',
      help: 'Price to Beat guard fail olursa node hata verip beklemeye alinır; kosullar duzelince tekrar dener.',
    },
    { key: 'notifyOnOrderSubmitted', label: 'Submit Bildirimi', input: 'checkbox', help: "CLOB'a emir basariyla gonderildiginde Telegram bildirimi gonder." },
    {
      key: 'notifyOnOrderPlaced',
      label: 'Emir Bildirimi (Telegram)',
      input: 'checkbox',
      help: 'Emir doldugunda / fill olustugunda Telegram bildirimi gonder.',
    },
    {
      key: 'notifyOnOrderNotFilled',
      label: 'Expire/Error Bildirimi',
      input: 'checkbox',
      help: 'Emir hic fill olmadan expired veya terminal error durumuna duserse Telegram bildirimi gonder.',
    },
    {
      key: 'notifyOnTriggerPriceBlocked',
      label: 'Tetik Fiyat Engel Bildirimi',
      input: 'checkbox',
      help: 'Trigger price guard emri engelleyince bildirim gonder.',
    },
    {
      key: 'notifyOnExecutionFloorBlocked',
      label: 'Execution Floor Engel Bildirimi',
      input: 'checkbox',
      help: 'Execution floor guard emri engelleyince bildirim gonder.',
    },
    {
      key: 'notifyOnMaxPriceBlocked',
      label: 'Max Fiyat Engel Bildirimi',
      input: 'checkbox',
      help: 'Max price guard emri engelleyince bildirim gonder.',
    },
    {
      key: 'retryOnMaxPriceBlock',
      label: 'Max Fiyat Bekle',
      input: 'checkbox',
      help: 'Max price guard orderi iptal etmek yerine beklemeye alir; fiyat dusunce yeniden dener.',
    },
    {
      key: 'notifyOnTpHit',
      label: 'Take Profit Bildirimi',
      input: 'checkbox',
      help: 'TP child emri doldurulunca bildirim gonder.',
    },
    {
      key: 'notifyOnSlHit',
      label: 'Stop Loss Bildirimi',
      input: 'checkbox',
      help: 'SL child emri doldurulunca bildirim gonder. Pair lock modunda bu alan ana bacak icindir.',
    },
    {
      key: 'pairLockStrategy',
      label: 'Pair Lock Stratejisi',
      input: 'select',
      options: [
        { label: 'Legacy pair lock', value: 'legacy' },
        { label: 'Edge pairlock v1', value: 'edge_pairlock_v1' },
        { label: 'Biased hedge v1', value: 'biased_hedge_v1' },
      ],
      help: 'Legacy mevcut iki bacak akisini kullanir. Edge pairlock v1 cost/edge kararidir. Biased hedge v1 erken dominant ana taraf, primary-fill sonrasi kucuk hedge ve bias invalidation/time-exit akisini kullanir.',
    },
    {
      key: 'pairLockDecisionQty',
      label: 'Edge Qty (share)',
      input: 'number',
      help: 'Edge pairlock v1 icin fresh pair veya tek taraf emirde hedef share adedi.',
    },
    {
      key: 'pairLockSingleEdgeThreshold',
      label: 'Tek Taraf Edge Esigi',
      input: 'number',
      help: 'Pair toplam uygun degilse tek taraf emir icin gereken minimum edge.',
    },
    {
      key: 'pairLockCostBuffer',
      label: 'Edge Cost Buffer',
      input: 'number',
      help: 'c_side hesabina eklenen buffer. Varsayilan 0.005.',
    },
    { key: 'biasedHedgePrimaryBudgetUsdc', label: 'Biased Primary Budget', input: 'number' },
    { key: 'biasedHedgeHedgeBudgetUsdc', label: 'Biased Hedge Budget', input: 'number' },
    { key: 'biasedHedgeMinDominantShare', label: 'Min Dominant Share', input: 'number' },
    { key: 'biasedHedgeMaxHedgeSpendRatio', label: 'Max Hedge Spend Ratio', input: 'number' },
    { key: 'biasedHedgePrimaryMinEdge', label: 'Primary Min Edge', input: 'number' },
    { key: 'biasedHedgePrimaryMinFinalQ', label: 'Primary Min q_final', input: 'number' },
    { key: 'biasedHedgeMaxPriceCent', label: 'Biased Max Price (cent)', input: 'number' },
    { key: 'biasedHedgeHighPriceCent', label: 'High Price Band (cent)', input: 'number' },
    { key: 'biasedHedgeHighPriceMinFinalQ', label: 'High Price Min q_final', input: 'number' },
    { key: 'biasedHedgeHighPriceMinEdge', label: 'High Price Min Edge', input: 'number' },
    { key: 'biasedHedgeHedgeOnlyIfPrimaryFilled', label: 'Hedge Primary Fill Bekler', input: 'checkbox' },
    { key: 'biasedHedgeHedgeMinPriceCent', label: 'Hedge Min Price (cent)', input: 'number' },
    { key: 'biasedHedgeHedgeMaxPriceCent', label: 'Hedge Max Price (cent)', input: 'number' },
    { key: 'biasedHedgeDisableNewPrimaryAfterSec', label: 'Primary Cutoff (elapsed sec)', input: 'number' },
    { key: 'biasedHedgeDisableAnyBuyAfterSec', label: 'Any Buy Cutoff (elapsed sec)', input: 'number' },
    { key: 'biasedHedgeMaxSideSwitchCount', label: 'Max Side Switch', input: 'number' },
    { key: 'biasedHedgeMaxPairedEffectiveCostCent', label: 'Max Paired Cost (cent)', input: 'number' },
    { key: 'biasedHedgeStopBiasInvalidationEnabled', label: 'Bias Invalidation', input: 'checkbox' },
    { key: 'biasedHedgeStopMinQFinalToHold', label: 'Hold Min q_final', input: 'number' },
    { key: 'biasedHedgeStopMinEdgeToHold', label: 'Hold Min Edge', input: 'number' },
    { key: 'biasedHedgeStopExitPctOnInvalidation', label: 'Invalidation Exit %', input: 'number' },
    { key: 'biasedHedgeStopPtbStopLossEnabled', label: 'Biased PTB Stop', input: 'checkbox' },
    { key: 'biasedHedgeStopPtbStopLossGapUsd', label: 'Biased PTB Stop Gap', input: 'number' },
    {
      key: 'biasedHedgeStopPtbStopLossTimeDecayMode',
      label: 'Biased PTB Stop Time Mode',
      input: 'select',
      options: [
        { label: 'tighten', value: 'tighten' },
        { label: 'relax', value: 'relax' },
        { label: 'none', value: 'none' },
      ],
    },
    {
      key: 'biasedHedgeStopTimeExitRulesJson',
      label: 'Biased Time Exit Rules JSON',
      input: 'text',
      help: 'JSON array: [{"elapsedSec":90,"remainingPct":60},{"elapsedSec":150,"remainingPct":0}]',
    },
    {
      key: 'pairMaxTotalCent',
      label: 'Pair Max Toplam (cent)',
      input: 'number',
      help: 'Bu bir ust limit tir. Ilk bacak hangi fiyattan dolarsa karsi bacak izin verilen efektif tavan `pairMaxTotalCent - leadFillPrice` ile hesaplanir; daha ucuz kombinasyonlar dogrudan kabul edilir.',
    },
    {
      key: 'pairSizingMode',
      label: 'Pair Sizing Modu',
      input: 'select',
      options: [
        { label: 'Manual', value: 'manual' },
        { label: 'Auto: kalan butce', value: 'auto_remaining_budget' },
      ],
      help: 'Manual modda karsi bacak tutari elle girilir. Auto modda ilk bacak `sizeUsdc` ile gider, kalan butce otomatik karsi bacaga ayrilir.',
    },
    {
      key: 'pairTotalBudgetUsdc',
      label: 'Toplam Pair Butcesi (USDC)',
      input: 'number',
      help: 'Auto modda toplam ayrilacak butce. Ilk bacak gercek harcamasi dusulduktan sonra kalan kisim karsi bacaga gider.',
    },
    {
      key: 'pairOrphanGraceMs',
      label: 'Pair Orphan Grace (ms)',
      input: 'number',
      help: 'Ilk fill sonrasi karsi bacak bu sure icinde kilitlenmezse acik exposure unwind edilir.',
    },
    {
      key: 'pairProtectiveUnwindEnabled',
      label: 'Pair Koruma Satışı',
      input: 'checkbox',
      help: 'Kapaliysa karsi bacak alinamadiginda lead pozisyon otomatik orphan unwind sell ile satilmaz; TP/SL/PTB SL kurallari pozisyonu yonetmeye devam eder.',
    },
    {
      key: 'pairIgnoreStopLossAfterLocked',
      label: 'İki Bacak Alındıysa SL Sayma',
      input: 'checkbox',
      help: 'Aktifken pair locked olduktan sonra ana ve karsi bacak SL/PTB-SL child emirleri olusturulmaz; lock oncesi acilan pair SL child emirleri iptal edilir.',
    },
    {
      key: 'notifyOnPairLocked',
      label: 'Pair Lock Bildirimi',
      input: 'checkbox',
      help: 'Iki bacak kar esigine oturup kilitlenince bildirim gonder.',
    },
    {
      key: 'notifyOnPairUnwind',
      label: 'Pair Unwind Bildirimi',
      input: 'checkbox',
      help: 'Orphan veya zorunlu unwind baslayinca bildirim gonder.',
    },
    {
      key: 'counterLegSizeUsdc',
      label: 'Karsi Bacak Tutar (USDC)',
      input: 'number',
      help: 'Counter bacak icin harcanacak USDC tutari. pair_lock modunda zorunludur.',
    },
    {
      key: 'counterLegEnabled',
      label: 'Karsi Bacak Aktif',
      input: 'checkbox',
      help: 'pair_lock modunda zorunludur.',
    },
    {
      key: 'counterLegOutcomeLabel',
      label: 'Karsi Bacak Outcome',
      input: 'select',
      options: [
        { label: 'opposite', value: 'opposite' },
        { label: 'Yes / Up', value: 'yes' },
        { label: 'No / Down', value: 'no' },
      ],
      help: 'Varsayilan opposite, ana bacak ters outcome tokenini otomatik secer.',
    },
    {
      key: 'counterLegTriggerCondition',
      label: 'Karsi Bacak Tetik',
      input: 'select',
      options: [
        { label: 'Yok', value: '' },
        { label: 'cross_above', value: 'cross_above' },
        { label: 'cross_below', value: 'cross_below' },
        { label: 'level_above', value: 'level_above' },
        { label: 'level_below', value: 'level_below' },
      ],
    },
    {
      key: 'counterLegTriggerPriceCent',
      label: 'Karsi Bacak Tetik Fiyat (cent)',
      input: 'number',
    },
    {
      key: 'counterLegMaxPriceCent',
      label: 'Karsi Bacak Max Fiyat (cent)',
      input: 'number',
      help: 'Opsiyonel statik ikinci bacak tavani. Gercek tavan `min(counterLegMaxPriceCent, pairMaxTotalCent - leadFillPrice)` olur.',
    },
    {
      key: 'counterLegPriceToBeatGuardEnabled',
      label: 'Karsi Bacak PTB Guard',
      input: 'checkbox',
    },
    {
      key: 'counterLegPriceToBeatMode',
      label: 'Karsi Bacak PTB Modu',
      input: 'select',
      options: PTB_MODE_OPTIONS,
    },
    {
      key: 'counterLegPriceToBeatMaxDiff',
      label: 'Karsi Bacak PTB Min Fark',
      input: 'number',
    },
    {
      key: 'counterLegPriceToBeatMaxDiffUnit',
      label: 'Karsi Bacak PTB Birimi',
      input: 'select',
      options: [
        { label: 'USD', value: 'usd' },
        { label: 'Cent', value: 'cent' },
      ],
    },
    {
      key: 'counterLegExecutionFloorGuardEnabled',
      label: 'Karsi Bacak Execution Floor',
      input: 'checkbox',
    },
    {
      key: 'counterLegExecutionFloorPriceCent',
      label: 'Karsi Bacak Floor Fiyat (cent)',
      input: 'number',
    },
    {
      key: 'counterLegTpEnabled',
      label: 'Karsi Bacak Take Profit',
      input: 'select',
      options: [
        { label: 'Kapali', value: 'false' },
        { label: 'Aktif', value: 'true' },
      ],
      help: 'Karsi bacak doldurulunca bagimsiz TP child sell acmaya izin verir. Karsi bacak TP kademeleriyle birlikte kullanilabilir.',
    },
    {
      key: 'counterLegTpPriceCent',
      label: 'Karsi Bacak TP Fiyat (cent)',
      input: 'number',
      help: 'Karsi bacak icin hard full-close TP seviyesi.',
    },
    {
      key: 'counterLegNotifyOnTpHit',
      label: 'Karsi Bacak TP Bildirimi',
      input: 'checkbox',
      help: 'Karsi bacak TP child emri doldurulunca bildirim gonder.',
    },
    {
      key: 'counterLegSlEnabled',
      label: 'Karsi Bacak Stop Loss',
      input: 'select',
      options: [
        { label: 'Kapali', value: 'false' },
        { label: 'Aktif', value: 'true' },
      ],
      help: 'Karsi bacak doldurulunca bagimsiz hard stop-loss child sell acmaya izin verir.',
    },
    {
      key: 'counterLegSlPriceCent',
      label: 'Karsi Bacak SL Fiyat (cent)',
      input: 'number',
      help: 'Karsi bacak icin hard full-close SL seviyesi.',
    },
    {
      key: 'counterLegSlTriggerPriceMode',
      label: 'Karsi Bacak SL Tetik Modu',
      input: 'select',
      options: [
        { label: 'Best Bid', value: 'best_bid' },
        { label: 'Composite (Legacy)', value: 'composite' },
        { label: 'Composite Safe', value: 'composite_safe' },
        { label: 'Composite Fast', value: 'composite_fast' },
        { label: 'Last Trade', value: 'last_trade' },
      ],
      help: 'Karsi bacak SL child icin kullanilacak tetik fiyat kaynagi.',
    },
    {
      key: 'counterLegPtbStopLossEnabled',
      label: 'Karsi Bacak PTB Gap Stop-Loss',
      input: 'checkbox',
      help: 'Karsi bacak icin bagimsiz PTB hard stop-loss child orderi acar. Bu alan da karsi outcome token fiyatini degil, PTB referansina gore directional gap\'i izler.',
    },
    {
      key: 'counterLegPtbStopLossGapUsd',
      label: 'Karsi Bacak PTB Gap Esiği',
      input: 'number',
      help: 'Karsi bacak directional gap esigi. Up/Yes icin current Chainlink - PTB, Down/No icin PTB - current Chainlink kullanilir; negatif deger karsi yone overshoot bekler.',
    },
    {
      key: 'counterLegPtbStopLossGapUnit',
      label: 'Karsi Bacak PTB Gap Birimi',
      input: 'select',
      options: [
        { label: 'USD', value: 'usd' },
        { label: 'Cent', value: 'cent' },
      ],
      help: 'Cent modunda 1 = $0.01. Sadece karsi bacak PTB hard stop icin kullanilir.',
    },
    {
      key: 'counterLegPtbStopLossTimeDecayMode',
      label: 'Karsi Bacak PTB SL Zaman Modu',
      input: 'select',
      options: [
        { label: 'tighten', value: 'tighten' },
        { label: 'relax', value: 'relax' },
        { label: 'none', value: 'none' },
      ],
      help: 'Karsi bacak PTB gap esiginin pencere ilerledikce nasil degisecegini belirler.',
    },
    {
      key: 'counterLegNotifyOnSlHit',
      label: 'Karsi Bacak SL Bildirimi',
      input: 'checkbox',
      help: 'Karsi bacak SL/PTB-SL child emri doldurulunca bildirim gonder.',
    },
    {
      key: 'counterLegRetryOnPriceToBeatGuardBlock',
      label: 'Karsi Bacak PTB Bekle',
      input: 'checkbox',
    },
    {
      key: 'counterLegRetryOnExecutionFloorGuardBlock',
      label: 'Karsi Bacak Floor Bekle',
      input: 'checkbox',
    },
    {
      key: 'counterLegRetryOnMaxPriceBlock',
      label: 'Karsi Bacak Max Bekle',
      input: 'checkbox',
    },
    {
      key: 'autoTuneEnabled',
      label: 'AutoTune Aktif',
      input: 'checkbox',
      help: 'Bu emir node’u icin AutoTune V1 advice yazimini acar. Canli emir davranisini veya published config’i degistirmez.',
    },
    {
      key: 'autoTuneMode',
      label: 'AutoTune Modu',
      input: 'select',
      options: [{ label: 'advice', value: 'advice' }],
      help: 'V1 yalnizca advice-only calisir; runtime override uygulamaz.',
    },
    {
      key: 'autoTuneSampleMarkets',
      label: 'AutoTune Sample Markets',
      input: 'number',
      help: 'Advice penceresine dahil edilecek completed market sayisi. Bos birakilirsa runner varsayilani kullanilir.',
    },
    {
      key: 'autoTuneMinEligibleMarkets',
      label: 'AutoTune Min Eligible Markets',
      input: 'number',
      help: 'Relax/tighten advice icin gereken minimum anlamli market sayisi.',
    },
    {
      key: 'autoTuneCooldownMarketsAfterAdvice',
      label: 'AutoTune Advice Cooldown',
      input: 'number',
      help: 'Advice yazildiktan sonra ayni node/scope icin kac market beklenir.',
    },
    {
      key: 'autoTuneDedupeSameAdviceForMarkets',
      label: 'AutoTune Dedupe Markets',
      input: 'number',
      help: 'Ayni advice’in tekrar yazilmasini engellemek icin bakilacak market sayisi.',
    },
    { key: 'refKey', label: 'Reference Key', input: 'text' },
];
