import type { NodeFieldSchema } from './types';

export const ACTION_PLACE_ORDER_ENTRY_QUALITY_FIELDS: NodeFieldSchema[] = [
  {
    key: 'priceToBeatIvEntryQualityPolicy',
    label: 'IV Entry Quality',
    input: 'checkbox',
    help: 'IV mismatch edge icin entry quality v2 filtresini acar.',
  },
  {
    key: 'priceToBeatIvNormalMaxPriceCent',
    label: 'IV Normal Max Ask',
    input: 'number',
    help: 'Bu cent ve alti normal entry olarak degerlendirilir.',
  },
  {
    key: 'priceToBeatIvPremiumMaxPriceCent',
    label: 'IV Premium Max Ask',
    input: 'number',
    help: 'Premium entry icin izin verilen en yuksek ask cent.',
  },
  {
    key: 'priceToBeatIvNoNewEntryBelowSeconds',
    label: 'IV No Entry Sn',
    input: 'number',
    help: 'Bu saniyenin altinda yeni IV entry bloklanir; esitlik degerlendirilir.',
  },
  {
    key: 'priceToBeatIvMinExpectedMoveBps',
    label: 'IV Min Move Bps',
    input: 'number',
    help: 'expected_move floor icin current_price * bps / 10000 kullanilir.',
  },
  {
    key: 'priceToBeatIvMinExpectedMoveUsd',
    label: 'IV Min Move Usd',
    input: 'number',
    help: 'expected_move floor icin mutlak USD alt siniri.',
  },
  {
    key: 'priceToBeatIvMinExpectedMoveMode',
    label: 'IV Move Floor Modu',
    input: 'select',
    options: [
      { label: 'Fixed', value: 'fixed' },
      { label: 'Adaptive', value: 'adaptive' },
    ],
    help: 'fixed eski min expected move floor davranisini korur; adaptive disagreement/spread/stale/noise durumunda bps flooru artirir.',
  },
  {
    key: 'priceToBeatIvAdaptiveMinExpectedMoveBaseBps',
    label: 'IV Adaptive Base Bps',
    input: 'number',
    help: 'Adaptive expected_move floor icin temiz kosul baz bps degeri.',
  },
  {
    key: 'priceToBeatIvAdaptiveMinExpectedMoveMinBps',
    label: 'IV Adaptive Min Bps',
    input: 'number',
    help: 'Adaptive bps clamp alt siniri.',
  },
  {
    key: 'priceToBeatIvAdaptiveMinExpectedMoveMaxBps',
    label: 'IV Adaptive Max Bps',
    input: 'number',
    help: 'Adaptive bps clamp ust siniri.',
  },
  {
    key: 'priceToBeatIvAdaptiveDisagreementBpsAdd',
    label: 'IV Disagree Bps Add',
    input: 'number',
    help: 'Binance/Chainlink disagreement orta esigi gecince bps floor uzerine eklenir.',
  },
  {
    key: 'priceToBeatIvAdaptiveStrongDisagreementBpsAdd',
    label: 'IV Strong Disagree Bps Add',
    input: 'number',
    help: 'Binance/Chainlink disagreement yuksek esigi gecince bps floor uzerine eklenir.',
  },
  {
    key: 'priceToBeatIvAdaptiveSpreadBpsAdd',
    label: 'IV Spread Bps Add',
    input: 'number',
    help: 'Spread 2c ve ustundeyken bps floor uzerine eklenir.',
  },
  {
    key: 'priceToBeatIvAdaptiveWideSpreadBpsAdd',
    label: 'IV Wide Spread Bps Add',
    input: 'number',
    help: 'Spread 3c ve ustundeyken bps floor uzerine eklenir.',
  },
  {
    key: 'priceToBeatIvAdaptiveStaleBpsAdd',
    label: 'IV Stale Bps Add',
    input: 'number',
    help: 'Chainlink/CEX age stale esigini gecince bps floor uzerine eklenir.',
  },
  {
    key: 'priceToBeatIvAdaptiveNoiseBpsAdd',
    label: 'IV Noise Bps Add',
    input: 'number',
    help: 'sigma_fast / sigma_eff noise esigini gecince bps floor uzerine eklenir.',
  },
  {
    key: 'priceToBeatIvGapStrengthMin60To45',
    label: 'IV Gap 60-45s',
    input: 'number',
    help: '60-45 saniye bandinda gereken minimum gap strength.',
  },
  {
    key: 'priceToBeatIvGapStrengthMin45To25',
    label: 'IV Gap 45-25s',
    input: 'number',
    help: '45-25 saniye bandinda gereken minimum gap strength.',
  },
  {
    key: 'priceToBeatIvGapStrengthMin25To10',
    label: 'IV Gap 25-10s',
    input: 'number',
    help: '25-10 saniye bandinda gereken minimum gap strength.',
  },
  {
    key: 'priceToBeatIvGapStrengthMin10To8',
    label: 'IV Gap 10-8s',
    input: 'number',
    help: '10-8 saniye bandinda gereken minimum gap strength.',
  },
  {
    key: 'priceToBeatIvBufferTrendGuardEnabled',
    label: 'IV Buffer Trend',
    input: 'checkbox',
    help: 'Signed same-side buffer retain kontrolunu acar.',
  },
  {
    key: 'priceToBeatIvBufferRetain5s',
    label: 'IV Retain 5s',
    input: 'number',
    help: 'Normal entry icin 5 sn buffer retain minimumu.',
  },
  {
    key: 'priceToBeatIvBufferRetain10s',
    label: 'IV Retain 10s',
    input: 'number',
    help: 'Normal entry icin 10 sn buffer retain minimumu.',
  },
  {
    key: 'priceToBeatIvPremiumBufferRetain5s',
    label: 'IV Prem Retain 5s',
    input: 'number',
    help: 'Premium entry icin 5 sn buffer retain minimumu.',
  },
  {
    key: 'priceToBeatIvPremiumBufferRetain10s',
    label: 'IV Prem Retain 10s',
    input: 'number',
    help: 'Premium entry icin 10 sn buffer retain minimumu.',
  },
  {
    key: 'priceToBeatIvSpikeFadeGuardEnabled',
    label: 'IV Spike Fade',
    input: 'checkbox',
    help: 'Yon uyumlu spike sonrasi retrace filtresini acar.',
  },
  {
    key: 'priceToBeatIvSpikeMultiplier',
    label: 'IV Spike Mult',
    input: 'number',
    help: '15 sn hareketin tipik harekete gore spike katsayisi.',
  },
  {
    key: 'priceToBeatIvSpikeRetraceRatio',
    label: 'IV Spike Retrace',
    input: 'number',
    help: 'Spike hareketinin retrace orani.',
  },
  {
    key: 'priceToBeatIvPremiumMaxSpreadCent',
    label: 'IV Prem Max Spread',
    input: 'number',
    help: 'Premium entry icin maksimum spread cent.',
  },
  {
    key: 'priceToBeatIvPremiumMaxChainlinkAgeMs',
    label: 'IV Prem Chainlink Age',
    input: 'number',
    help: 'Premium entry icin maksimum Chainlink age ms.',
  },
  {
    key: 'priceToBeatIvChainlinkStaleMs',
    label: 'IV Chainlink Stale Ms',
    input: 'number',
    help: 'IV engine genel Chainlink provider-age esigi.',
  },
  {
    key: 'priceToBeatIvCexAlignMaxUsd',
    label: 'IV CEX Align Usd',
    input: 'number',
    help: 'Chainlink ile CEX fiyat farki icin USD align toleransi.',
  },
  {
    key: 'priceToBeatIvCexAlignMaxBps',
    label: 'IV CEX Align Bps',
    input: 'number',
    help: 'Chainlink ile CEX fiyat farki icin bps align toleransi.',
  },
  {
    key: 'priceToBeatIvCexOpenGapConsensusGuardEnabled',
    label: 'IV CEX Open Gap',
    input: 'checkbox',
    help: 'Binance + aktif anchor 5m open-gap consensus guard paketini acar.',
  },
  {
    key: 'priceToBeatIvCexOpenGapMinUsd',
    label: 'IV CEX Gap Min Usd',
    input: 'number',
    help: 'Venue supporting state icin minimum selected-side gap USD.',
  },
  {
    key: 'priceToBeatIvCexOpenGapMinZ',
    label: 'IV CEX Gap Min Z',
    input: 'number',
    help: 'Venue supporting state icin expected_move_eff carpan esigi.',
  },
  {
    key: 'priceToBeatIvCexMagnitudeGuardEnabled',
    label: 'IV CEX Magnitude',
    input: 'checkbox',
    help: 'CEX direction strong olsa bile conservative gap required gap oranini kontrol eder.',
  },
  {
    key: 'priceToBeatIvCexMagnitudeShallowRatio',
    label: 'IV CEX Shallow Ratio',
    input: 'number',
    help: 'Bu oranin altinda CEX magnitude shallow sayilir.',
  },
  {
    key: 'priceToBeatIvCexMagnitudeModerateRatio',
    label: 'IV CEX Moderate Ratio',
    input: 'number',
    help: 'Bu oran ve uzeri CEX magnitude strong sayilir.',
  },
  {
    key: 'priceToBeatIvChainlinkStaleStrongGapExceptionEnabled',
    label: 'IV Stale Strong Gap',
    input: 'checkbox',
    help: 'Clean CEX teyitli strong-gap sinyalde Chainlink stale hard block yerine penalty yolunu kullanir.',
  },
  {
    key: 'priceToBeatIvChainlinkStaleStrongGapMinGapStrength',
    label: 'IV Stale Strong Gap Min',
    input: 'number',
    help: 'Exception icin gereken minimum entry-quality gap strength.',
  },
  {
    key: 'priceToBeatIvChainlinkStaleStrongGapMaxOracleAgeMs',
    label: 'IV Stale Strong Gap Max Age',
    input: 'number',
    help: 'Exception icin izin verilen maksimum oracle price age ms.',
  },
  {
    key: 'priceToBeatIvChainlinkStaleStrongGapRequireCexConfirmed',
    label: 'IV Stale Require CEX',
    input: 'checkbox',
    help: 'Exception icin CEX confirmation zorunlu olsun.',
  },
  {
    key: 'priceToBeatIvChainlinkStaleStrongGapRequireBybitHit',
    label: 'IV Stale Require Anchor',
    input: 'checkbox',
    help: 'Exception icin aktif CEX anchor threshold hit zorunlu olsun.',
  },
  {
    key: 'priceToBeatIvChainlinkStaleStrongGapRequireSecondaryCex',
    label: 'IV Stale Require Secondary',
    input: 'checkbox',
    help: 'Exception icin Binance veya Coinbase secondary confirmation zorunlu olsun.',
  },
  {
    key: 'priceToBeatIvChainlinkCexLagGuardEnabled',
    label: 'IV CEX Lag Guard',
    input: 'checkbox',
    help: 'Chainlink-CEX diff yuksek ve book dislocation sertse entry bloklar.',
  },
  {
    key: 'priceToBeatIvExecutionLimitByVwapEnabled',
    label: 'IV VWAP Limit',
    input: 'checkbox',
    help: 'Submit limit price degerini expected VWAP + slippage ile clamp eder.',
  },
  {
    key: 'priceToBeatIvExecutionVwapMaxSlippageCent',
    label: 'IV VWAP Slip Cent',
    input: 'number',
    help: 'Expected VWAP uzerine izin verilen maksimum cent slippage.',
  },
  {
    key: 'priceToBeatIvEntryQualityChainlinkMaxAgeMs',
    label: 'IV Chainlink Max Age Ms',
    input: 'number',
    help: 'Bu provider-age ustundeki Chainlink verisi son 30 sn entryde bloklanir; erken pencerede ekstra edge/gap cezasi alir.',
  },
  {
    key: 'priceToBeatIvEntryQualityHighRiskUnderSec',
    label: 'IV High Risk Sn',
    input: 'number',
    help: 'CEX neutral/stale ve Chainlink stale icin gec entry penceresi.',
  },
  {
    key: 'priceToBeatIvEntryQualityHighRiskAskCent',
    label: 'IV High Risk Ask',
    input: 'number',
    help: 'Bu ask cent ve ustu entrylerde CEX/Chainlink/spread politikasi daha sert uygulanir.',
  },
  {
    key: 'priceToBeatIvEntryQualityHighPriceMaxSpreadCent',
    label: 'IV High Ask Max Spread',
    input: 'number',
    help: 'Ask high-risk seviyesindeyken izin verilen maksimum spread cent.',
  },
  {
    key: 'priceToBeatIvEntryQualityMaxSpreadCent',
    label: 'IV Max Spread',
    input: 'number',
    help: 'Normal ask seviyelerinde izin verilen maksimum spread cent.',
  },
  {
    key: 'priceToBeatIvEntryQualityNeutralEdgePenalty',
    label: 'IV Neutral Edge Ceza',
    input: 'number',
    help: 'CEX neutral/unconfirmed + late high-price entryde required edge uzerine eklenir.',
  },
  {
    key: 'priceToBeatIvEntryQualityNeutralGapStrengthPenalty',
    label: 'IV Neutral Gap Ceza',
    input: 'number',
    help: 'CEX neutral/unconfirmed + late high-price entryde required gap strength uzerine eklenir.',
  },
  {
    key: 'priceToBeatIvEntryQualityStaleEdgePenalty',
    label: 'IV Stale Edge Ceza',
    input: 'number',
    help: 'CEX/Chainlink stale ama hard block disinda kalan entrylerde required edge uzerine eklenir.',
  },
  {
    key: 'priceToBeatIvEntryQualityStaleGapStrengthPenalty',
    label: 'IV Stale Gap Ceza',
    input: 'number',
    help: 'CEX/Chainlink stale ama hard block disinda kalan entrylerde required gap strength uzerine eklenir.',
  },
];
