import type { ConditionOperator } from './types';

export const TIMEFRAME_TO_CYCLE_DURATION_SECS: Record<string, number> = { '5m': 300, '15m': 900 };

export const RESOLVE_MARKET_SCOPE_TO_ASSET_TIMEFRAME: Record<string, { asset: string; timeframe: string }> = {
  btc_5m_updown: { asset: 'btc', timeframe: '5m' },
  btc_15m_updown: { asset: 'btc', timeframe: '15m' },
  eth_5m_updown: { asset: 'eth', timeframe: '5m' },
  eth_15m_updown: { asset: 'eth', timeframe: '15m' },
  sol_5m_updown: { asset: 'sol', timeframe: '5m' },
  sol_15m_updown: { asset: 'sol', timeframe: '15m' },
  xrp_5m_updown: { asset: 'xrp', timeframe: '5m' },
  xrp_15m_updown: { asset: 'xrp', timeframe: '15m' },
};

export const QUICK_PRESET_BUY_SELL_REF_KEYS = new Set([
  'preset_sell_current_position',
  'preset_buy_current_position',
]);

export const QUICK_PRESET_BUY_SELL_KINDS = new Set([
  'sell_current_position',
  'buy_current_position',
]);

export const PRESET_PLACE_ORDER_KINDS = new Set([
  'place_order',
  ...QUICK_PRESET_BUY_SELL_KINDS,
]);

export const TRIGGER_MARKET_ONCE_SCOPE_VERSION = 2;
export const CONDITION_OPERATORS: ConditionOperator[] = ['>', '>=', '<', '<=', '==', '!='];

export const NUMERIC_KEYS = new Set([
  'pollIntervalMs',
  'minIntervalMs',
  'triggerPrice',
  'triggerPriceCent',
  'maxPriceCent',
  'sourceTradeId',
  'minProgressPct',
  'minPositionQty',
  'delayMs',
  'maxAttempts',
  'sizeUsdc',
  'sizePct',
  'targetQty',
  'targetNotionalUsdc',
  'minPriceDistanceCent',
  'maxTriggers',
  'builderOrderId',
  'baseShares',
  'baseUsdc',
  'basePriceUsdc',
  'dcaLevels',
  'nearStep',
  'stepMult',
  'sizeMult',
  'cutoffMin',
  'tpProfitPct',
  'slLossPct',
  'slSpreadPct',
  'confirmationMs',
  'entryPriceCent',
  'tpPriceCent',
  'counterLegTpPriceCent',
  'slPriceCent',
  'ptbStopLossGapUsd',
  'counterLegSlPriceCent',
  'counterLegPtbStopLossGapUsd',
  'priceToBeatMaxDiff',
  'priceToBeatStopLossBumpAmount',
  'priceToBeatStopLossBumpMaxValue',
  'priceToBeatMaxPriceRelaxMissCount',
  'priceToBeatMaxPriceRelaxHistoryCount',
  'priceToBeatMaxPriceRelaxMinValue',
  'priceToBeatMaxPriceRelaxMinDepthUsd',
  'priceToBeatMaxPriceRelaxStepValue',
  'priceToBeatIvStalePenaltyMs',
  'priceToBeatIvStaleGapStrengthPenalty',
  'priceToBeatIvNegativeVelocityGapStrengthPenalty',
  'priceToBeatIvBinanceMissingAskThresholdCent',
  'priceToBeatIvBinanceMissingPenalty',
  'priceToBeatIvMinAdjustedMargin',
  'priceToBeatIvMinFinalQ',
  'priceToBeatIvBinanceDisagreementThreshold',
  'priceToBeatIvBinanceDisagreementPenalty',
  'priceToBeatIvLargeBinanceDisagreementThreshold',
  'priceToBeatIvLargeBinanceDisagreementPenalty',
  'priceToBeatIvBookLeadUnderSec',
  'priceToBeatIvBookLeadMinMidDiff',
  'priceToBeatIvOppositeMidBlockCent',
  'priceToBeatIvTooGoodToBeTrueGap',
  'priceToBeatIvModelBookGapWarn',
  'priceToBeatIvModelBookGapHard',
  'priceToBeatIvModelBookWarnThresholdPenalty',
  'priceToBeatIvModelBookWarnGapPenalty',
  'priceToBeatIvDepthMaxSlippage',
  'priceToBeatIvLateHighPriceSoftUnderSec',
  'priceToBeatIvLateHighPriceAskCent',
  'priceToBeatIvLateHighPriceSelectedMidSoftCent',
  'priceToBeatIvLateHighPriceThresholdPenalty',
  'priceToBeatIvLateHighPriceSelectedMidHardCent',
  'priceToBeatIvLateHighPriceMinGapUsd',
  'priceToBeatIvParticipationAfterMinutes',
  'priceToBeatIvParticipationLongAfterMinutes',
  'priceToBeatIvParticipationCredit',
  'priceToBeatIvParticipationLongCredit',
  'priceToBeatIvParticipationMinThreshold',
  'priceToBeatIvRequireBinanceFreshUnderSec',
  'priceToBeatIvBinanceMaxStaleMs',
  'priceToBeatIvDropZBlockThreshold',
  'priceToBeatIvProtectionSoftThresholdPenalty',
  'priceToBeatIvProtectionSoftGapStrengthPenalty',
  'reentryPriceToBeatMaxDiff',
  'priceToBeatTriggerMinGap',
  'priceToBeatTriggerMaxGap',
  'reentryMaxAttempts',
  'reentryMinPriceCent',
  'reentryMaxPriceCent',
  'reentryCooldownSec',
  'reentryThresholdDecay',
  'reentryMaxPriceTightenBps',
  'priceToBeatStopLossBumpDecayWindows',
  'executionFloorPriceCent',
  'cycleWindowStartSec',
  'cycleWindowEndSec',
  'pairLockDecisionQty',
  'pairLockSingleEdgeThreshold',
  'pairLockCostBuffer',
  'adaptiveMaxPriceMissCount',
  'adaptiveMaxPriceRequiredGoodMissCount',
  'adaptiveMaxPriceRelaxCreditCent',
  'adaptiveMaxPriceMaxRelaxCreditCent',
  'adaptiveMaxPriceHardCapCent',
  'adaptiveMaxPriceExtraBufferCent',
  'adaptiveMaxPricePairBufferCent',
  'adaptiveMaxPriceSizeMultiplier',
  'adaptiveMaxPriceWindowStartSec',
  'adaptiveMaxPriceWindowEndSec',
  'adaptiveMaxPriceLateRelaxCutoffS',
  'adaptiveMaxPriceLateRiskAfterSec',
  'adaptiveMaxPriceLateExtraBufferCent',
  'adaptiveMaxPriceLateSizeMultiplier',
  'adaptiveMaxPriceSlCooldownMarkets',
  'adaptiveMaxPriceNotifyMinIntervalSec',
  'adaptiveMaxPriceSummaryEveryMarkets',
  'manualAdaptiveWindowStartSec',
  'manualAdaptiveWindowEndSec',
  'manualAdaptiveVolumeNormalLt',
  'manualAdaptiveVolumeElevatedLt',
  'manualAdaptiveVolumeHighLt',
  'manualAdaptiveTrendDeltaUsd',
  'manualAdaptiveNormalFlatMaxPriceSubCent',
  'manualAdaptiveNormalFlatSizeMultiplier',
  'manualAdaptiveNormalFlatPtbGapAddCent',
  'manualAdaptiveNormalCollapsingMaxPriceCent',
  'manualAdaptiveNormalCollapsingSizeMultiplier',
  'manualAdaptiveNormalCollapsingPtbGapAddCent',
  'manualAdaptiveElevatedMaxPriceCent',
  'manualAdaptiveElevatedSizeMultiplier',
  'manualAdaptiveElevatedPtbGapAddCent',
  'manualAdaptiveHighMaxPriceCent',
  'manualAdaptiveHighSizeMultiplier',
  'manualAdaptiveHighPtbGapAddCent',
  'manualAdaptiveAfterSlMaxPriceSubCent',
  'manualAdaptiveAfterSlPtbGapAddCent',
  'manualAdaptiveSlCooldownMarkets',
  'manualAdaptivePairBufferCent',
  'manualAdaptiveNotifyMinIntervalSec',
  'biasedHedgePrimaryBudgetUsdc',
  'biasedHedgeHedgeBudgetUsdc',
  'biasedHedgeMinDominantShare',
  'biasedHedgeMaxHedgeSpendRatio',
  'biasedHedgePrimaryMinEdge',
  'biasedHedgePrimaryMinFinalQ',
  'biasedHedgeMaxPriceCent',
  'biasedHedgeHighPriceCent',
  'biasedHedgeHighPriceMinFinalQ',
  'biasedHedgeHighPriceMinEdge',
  'biasedHedgeHedgeMinPriceCent',
  'biasedHedgeHedgeMaxPriceCent',
  'biasedHedgeDisableNewPrimaryAfterSec',
  'biasedHedgeDisableAnyBuyAfterSec',
  'biasedHedgeMaxSideSwitchCount',
  'biasedHedgeMaxPairedEffectiveCostCent',
  'biasedHedgeStopMinQFinalToHold',
  'biasedHedgeStopMinEdgeToHold',
  'biasedHedgeStopExitPctOnInvalidation',
  'biasedHedgeStopPtbStopLossGapUsd',
  'pairMaxTotalCent',
  'pairTotalBudgetUsdc',
  'pairOrphanGraceMs',
  'counterLegTriggerPriceCent',
  'counterLegMaxPriceCent',
  'counterLegPriceToBeatMaxDiff',
  'counterLegExecutionFloorPriceCent',
  'counterLegSizeUsdc',
  'autoTuneSampleMarkets',
  'autoTuneMinEligibleMarkets',
  'autoTuneCooldownMarketsAfterAdvice',
  'autoTuneDedupeSameAdviceForMarkets',
]);

export const BOOLEAN_KEYS = new Set([
  'failOnMissingMarket',
  'requireYesNoTokens',
  'requireTokenId',
  'tpEnabled',
  'slEnabled',
  'ptbStopLossEnabled',
  'triggerPriceGuardEnabled',
  'executionFloorGuardEnabled',
  'priceToBeatGuardEnabled',
  'priceToBeatMaxPriceRelaxEnabled',
  'priceToBeatStopLossBumpEnabled',
  'priceToBeatTriggerEnabled',
  'priceToBeatIvBookLeadGuardEnabled',
  'priceToBeatIvBlockOnOppositeBookLead',
  'priceToBeatIvDepthGuardEnabled',
  'priceToBeatIvRequireBinanceSameDirection',
  'priceToBeatIvParticipationCreditEnabled',
  'priceToBeatIvMomentumProtectionEnabled',
  'priceToBeatIvAdaptiveRedBlock',
  'retryOnTriggerPriceGuardBlock',
  'retryOnExecutionFloorGuardBlock',
  'retryOnPriceToBeatGuardBlock',
  'notifyOnOrderSubmitted',
  'notifyOnOrderPlaced',
  'notifyOnOrderNotFilled',
  'notifyOnTriggerPriceBlocked',
  'notifyOnExecutionFloorBlocked',
  'notifyOnPriceToBeatGapBlocked',
  'notifyOnMaxPriceBlocked',
  'retryOnMaxPriceBlock',
  'notifyOnTpHit',
  'counterLegTpEnabled',
  'counterLegNotifyOnTpHit',
  'notifyOnSlHit',
  'counterLegSlEnabled',
  'counterLegPtbStopLossEnabled',
  'counterLegNotifyOnSlHit',
  'reenterOnSlHit',
  'reentrySkipCurrentWindow',
  'stagedSlReentryOnlyAfterAllStages',
  'autoSellOnWindowEnd',
  'counterLegEnabled',
  'counterLegPriceToBeatGuardEnabled',
  'counterLegExecutionFloorGuardEnabled',
  'counterLegRetryOnPriceToBeatGuardBlock',
  'counterLegRetryOnExecutionFloorGuardBlock',
  'counterLegRetryOnMaxPriceBlock',
  'buyFillLockEnabled',
  'releaseBuyFillLockOnStopLoss',
  'pairProtectiveUnwindEnabled',
  'pairIgnoreStopLossAfterLocked',
  'adaptiveMaxPriceLateRiskEnabled',
  'notifyOnAdaptiveMaxPriceEvaluated',
  'notifyOnAdaptiveMaxPriceRelax',
  'notifyOnAdaptiveMaxPriceRelaxSl',
  'notifyOnAdaptiveMaxPriceNoRelaxImportant',
  'notifyOnAdaptiveMaxPriceMissResolved',
  'notifyOnAdaptiveMaxPriceCooldown',
  'notifyOnAdaptiveMaxPriceSummary',
  'notifyOnAdaptiveMaxPriceAllNoRelax',
  'adaptiveMaxPriceNotifyIncludePayload',
  'notifyOnManualAdaptiveRiskBlock',
  'notifyOnManualAdaptiveRiskStrict',
  'notifyOnManualAdaptiveRiskSlBump',
  'notifyOnManualAdaptiveRiskSummary',
  'manualAdaptiveNotifyIncludePayload',
  'biasedHedgeHedgeOnlyIfPrimaryFilled',
  'biasedHedgeStopBiasInvalidationEnabled',
  'biasedHedgeStopPtbStopLossEnabled',
  'notifyOnPairLocked',
  'notifyOnPairUnwind',
  'autoTuneEnabled',
]);

export const CONTEXT_BASE_KEYS = new Set([
  'sourceTradeId',
  'marketSlug',
  'tokenId',
  'outcomeLabel',
  'autoClaimEnabled',
]);
