import type { NodeFieldSchema } from './types';

export const NODE_FIELD_SCHEMAS: Record<string, NodeFieldSchema[]> = {
  'trigger.market_price': [
    {
      key: 'marketMode',
      label: 'Market Modu',
      input: 'select',
      options: [
        { label: 'Sabit (fixed)', value: 'fixed' },
        { label: 'Otomatik Scope (auto_scope)', value: 'auto_scope' },
      ],
    },
    { key: 'marketSlug', label: 'Market Slug', input: 'text' },
    {
      key: 'marketScope',
      label: 'Market Scope',
      input: 'select',
      options: [
        { label: 'BTC 5m', value: 'btc_5m_updown' },
        { label: 'BTC 15m', value: 'btc_15m_updown' },
        { label: 'ETH 5m', value: 'eth_5m_updown' },
        { label: 'ETH 15m', value: 'eth_15m_updown' },
        { label: 'SOL 5m', value: 'sol_5m_updown' },
        { label: 'SOL 15m', value: 'sol_15m_updown' },
        { label: 'XRP 5m', value: 'xrp_5m_updown' },
        { label: 'XRP 15m', value: 'xrp_15m_updown' },
      ],
    },
    {
      key: 'marketSelection',
      label: 'Secim Stratejisi',
      input: 'select',
      options: [{ label: 'latest_by_slug', value: 'latest_by_slug' }],
    },
    {
      key: 'protectionMode',
      label: 'Underlying Koruma',
      input: 'select',
      options: [
        { label: 'Kapali (off)', value: 'off' },
        { label: 'Asset teyidi', value: 'underlying_confirm' },
      ],
      help: 'Koruma secilen auto_scope assetine otomatik baglanir. BTC scope BTC ile, XRP scope XRP ile dogrulanir.',
    },
    {
      key: 'protectionPreset',
      label: 'Koruma Preseti',
      input: 'select',
      options: [
        { label: 'Loose', value: 'loose' },
        { label: 'Balanced', value: 'balanced' },
        { label: 'Strict', value: 'strict' },
      ],
      help: 'Balanced varsayilandir. Ayrica manuel asset secimi yoktur; secilen scope kullanilir.',
    },
    {
      key: 'cycleWindowMode',
      label: 'Cycle Pencere Modu',
      input: 'select',
      options: [
        { label: 'Tamamı (kapalı)', value: 'off' },
        { label: 'İlk N saniye (first)', value: 'first' },
        { label: 'Son N saniye (last)', value: 'last' },
        { label: 'Ozel Aralik (custom_range)', value: 'custom_range' },
      ],
      help: 'Cycle icinde sadece belirli bir zaman penceresinde tetik degerlendirilir. Auto-scope + `last` modunda son pencereye girdiginde ilk gorulen uygun fiyat da tetikleyebilir; fixed markette gercek cross aranir.',
    },
    {
      key: 'cycleWindowSecs',
      label: 'Pencere Süresi (saniye)',
      input: 'number',
      help: 'Kac saniye boyunca tetik degerlendirilecek. Or: 5m cycle, last 60 -> son 60sn. Auto-scope + `last` modunda son pencereye in-zone giris kabul edilir; fixed markette pencere icinde gercek gecis aranir.',
    },
    {
      key: 'cycleWindowStartSec',
      label: 'Pencere Baslangic (saniye)',
      input: 'number',
      help: 'Cycle baslangicindan itibaren kac saniye sonra pencere acilir. Ornek: 5m cycle, 40 -> cycle basladigindan 40sn sonra. Cycle suresi: 5m=300sn, 15m=900sn.',
    },
    {
      key: 'cycleWindowEndSec',
      label: 'Pencere Bitis (saniye)',
      input: 'number',
      help: 'Cycle baslangicindan itibaren kac saniye sonra pencere kapanir. startSec < endSec olmali. Ornek: 5m cycle, 300 -> cycle sonuna kadar. Cycle suresi: 5m=300sn, 15m=900sn.',
    },
    {
      key: 'autoSellOnWindowEnd',
      label: 'Pencere Bitince Pozisyonu Kapat',
      input: 'checkbox',
      help: 'Aktifken, custom_range penceresi bittiginde acik pozisyon varsa otomatik olarak market emriyle satar. Stop-loss mantigi ile calisir.',
    },
    {
      key: 'repeatMode',
      label: 'Tetik Modu',
      input: 'select',
      options: [
        { label: '1 Kere (once)', value: 'once' },
        { label: 'Döngü (loop)', value: 'loop' },
      ],
    },
    {
      key: 'onceScope',
      label: 'Once Scope',
      input: 'select',
      options: [
        { label: 'Run', value: 'run' },
        { label: 'Market', value: 'market' },
      ],
      help: '`run` ilk basarili tetikten sonra workflow run boyunca tekrar almaz. `market` her yeni auto_scope markette bir kez daha tetikleyebilir. Auto-scope + once varsayilani markettir.',
    },
    { key: 'minIntervalMs', label: 'Kontrol Aralığı (ms)', input: 'number', help: 'Varsayılan: 10000 (10sn). Minimum: 250ms.' },
    { key: 'confirmationMs', label: 'Onay Süresi (ms)', input: 'number', help: 'Cross sonrası fiyatın eşikte kalması gereken süre. Boş = onay kapalı, 0 = anında tetik.' },
    {
      key: 'priceToBeatTriggerEnabled',
      label: 'Price-to-Beat Gate',
      input: 'checkbox',
      help: 'Aktifken tetik price-to-beat farki araligina gore degerlendirilir. Fiyat kosulu bos birakilabilir. Sadece auto_scope.',
    },
    {
      key: 'priceToBeatTriggerUnit',
      label: 'Fark Birimi',
      input: 'select',
      options: [
        { label: 'USD', value: 'usd' },
        { label: 'Cent', value: 'cent' },
      ],
      help: 'USD: dolar cinsinden. Cent: sent cinsinden. Ornek: cent modunda 1 = $0.01.',
    },
    {
      key: 'priceToBeatTriggerMinGap',
      label: 'Minimum Fark',
      input: 'number',
      help: 'Price-to-beat farki bu degerin altindaysa tetik ateslenmez.',
    },
    {
      key: 'priceToBeatTriggerMaxGap',
      label: 'Tavan Fark',
      input: 'number',
      help: 'Price-to-beat farki bu degerin ustundeyse tetik ateslenmez. Opsiyonel.',
    },
    {
      key: 'priceMode',
      label: 'Fiyat Kaynağı',
      input: 'select',
      options: [
        { label: 'composite (önerilen)', value: 'composite' },
        { label: 'site display (Polymarket UI)', value: 'site_display' },
        { label: 'midpoint', value: 'midpoint' },
        { label: 'raw trade (fallbacklı)', value: 'raw' },
        { label: 'last trade (strict)', value: 'last_trade' },
        { label: 'best bid (satış için)', value: 'best_bid' },
        { label: 'best ask (alış için)', value: 'best_ask' },
      ],
      help: 'composite: cross_above/level_above icin best_bid ile last_trade fiyatinin yuksek olanini, cross_below/level_below icin dusuk olanini kullanir. site_display: Polymarket UI fiyati; spread 10c altindaysa midpoint, ustundeyse son islem fiyati. midpoint: best bid/ask ortalamasi. raw: son islem fiyatini kullanir, yoksa midpoint fallback yapar. last_trade: sadece son islem fiyatini kullanir, fallback yapmaz. best_bid: en iyi alim fiyati. best_ask: en iyi satim fiyati.',
    },
  ],
  'trigger.sell_progress': [
    { key: 'sourceTradeId', label: 'Source Trade ID', input: 'number' },
    { key: 'minProgressPct', label: 'Minimum İlerleme (%)', input: 'number' },
    { key: 'varKey', label: 'Değişken Anahtarı', input: 'text', placeholder: 'sell_progress_pct' },
    { key: 'minIntervalMs', label: 'Minimum Interval (ms)', input: 'number' },
  ],
  'trigger.open_positions': [
    { key: 'sourceTradeId', label: 'Source Trade ID', input: 'number' },
    { key: 'marketSlug', label: 'Market Slug', input: 'text' },
    { key: 'tokenId', label: 'Token ID', input: 'text' },
    { key: 'outcomeLabel', label: 'Outcome Label', input: 'text' },
    {
      key: 'triggerCondition',
      label: 'Fiyat Tetik Koşulu',
      input: 'select',
      options: [
        { label: 'Yok', value: '' },
        { label: 'cross_above', value: 'cross_above' },
        { label: 'cross_below', value: 'cross_below' },
        { label: 'level_above', value: 'level_above' },
        { label: 'level_below', value: 'level_below' },
      ],
    },
    {
      key: 'triggerPriceCent',
      label: 'Fiyat Eşiği (cent)',
      input: 'number',
      help: 'Örn: 70 girersen 70c.',
    },
    {
      key: 'maxPriceCent',
      label: 'Tavan Fiyati (cent)',
      input: 'number',
      help: 'Opsiyonel. cross_above/level_above ile birlikte kullanirsan triggerPrice ile bu tavan arasina girildiginde tetik sayilir; tavanin ustu tetiklenmez.',
    },
    {
      key: 'minIntervalMs',
      label: 'Minimum Interval (ms)',
      input: 'number',
      help: 'Fiyat tetik koşulu aktifse kullanılmaz; websocket event tetikler.',
    },
  ],
  'trigger.position_drawdown': [
    { key: 'marketSlug', label: 'Market Slug', input: 'text' },
    { key: 'outcomeLabel', label: 'Outcome Label', input: 'text' },
    {
      key: 'entryPriceCent',
      label: 'Entry Fiyati (cent)',
      input: 'number',
      help: 'Pozisyona bakmadan drawdown hesabi bu entry fiyatina gore yapilir. Ornek: 80 => $0.80',
    },
    {
      key: 'combineMode',
      label: 'Kural Birlesimi',
      input: 'select',
      options: [
        { label: 'Otomatik', value: '' },
        { label: 'AND (hepsi)', value: 'and' },
        { label: 'OR (herhangi biri)', value: 'or' },
      ],
      help: 'Bos birakirsan: tek kural varsa tek kural, birden fazla kural varsa OR uygulanir.',
    },
    {
      key: 'minIntervalMs',
      label: 'Minimum Interval (ms)',
      input: 'number',
      help: 'Varsayilan 250ms. Minimum 250ms.',
    },
    { key: 'varPrefix', label: 'Degisken Prefix', input: 'text', placeholder: 'drawdown' },
  ],
  'trigger.time_window': [
    { key: 'startAt', label: 'Başlangıç Zamanı', input: 'datetime-local' },
    { key: 'endAt', label: 'Bitiş Zamanı', input: 'datetime-local' },
    { key: 'varKey', label: 'Değişken Anahtarı', input: 'text', placeholder: 'time_window_open' },
    { key: 'minIntervalMs', label: 'Minimum Interval (ms)', input: 'number' },
  ],
  'logic.if': [
    { key: 'comment', label: 'Açıklama', input: 'textarea' },
  ],
  'logic.switch': [
    { key: 'comment', label: 'Açıklama', input: 'textarea' },
  ],
  'logic.delay': [
    { key: 'delayMs', label: 'Gecikme (ms)', input: 'number' },
  ],
  'logic.retry': [
    { key: 'maxAttempts', label: 'Maksimum Deneme', input: 'number' },
  ],
  'action.resolve_market': [
    {
      key: 'asset',
      label: 'Asset',
      input: 'select',
      options: [
        { label: 'BTC', value: 'btc' },
        { label: 'ETH', value: 'eth' },
        { label: 'SOL', value: 'sol' },
        { label: 'XRP', value: 'xrp' },
      ],
    },
    {
      key: 'timeframe',
      label: 'Timeframe',
      input: 'select',
      options: [
        { label: '5m', value: '5m' },
        { label: '15m', value: '15m' },
      ],
      help: 'Market slug bu secime gore otomatik hesaplanir.',
    },
    {
      key: 'selection',
      label: 'Secim Stratejisi',
      input: 'select',
      options: [{ label: 'latest_by_slug', value: 'latest_by_slug' }],
    },
    {
      key: 'outcomeLabel',
      label: 'Outcome',
      input: 'select',
      options: [
        { label: 'yes', value: 'yes' },
        { label: 'no', value: 'no' },
      ],
      help: 'tokenId secimi bu outcome alanina gore yapilir.',
    },
    {
      key: 'failOnMissingMarket',
      label: 'Market Yoksa Hata',
      input: 'select',
      options: [
        { label: 'true', value: 'true' },
        { label: 'false', value: 'false' },
      ],
    },
    {
      key: 'requireYesNoTokens',
      label: 'YES/NO Token Zorunlu',
      input: 'select',
      options: [
        { label: 'true', value: 'true' },
        { label: 'false', value: 'false' },
      ],
    },
    {
      key: 'requireTokenId',
      label: 'Secilen Token Zorunlu',
      input: 'select',
      options: [
        { label: 'true', value: 'true' },
        { label: 'false', value: 'false' },
      ],
    },
    { key: 'varPrefix', label: 'Degisken Prefix', input: 'text', placeholder: 'resolved_market' },
  ],
  'action.dual_dca': [
    { key: 'sourceTradeId', label: 'Source Trade ID', input: 'number' },
    {
      key: 'asset',
      label: 'Coin',
      input: 'select',
      options: [
        { label: 'BTC', value: 'btc' },
        { label: 'ETH', value: 'eth' },
        { label: 'SOL', value: 'sol' },
        { label: 'XRP', value: 'xrp' },
      ],
    },
    {
      key: 'timeframe',
      label: 'Market Period',
      input: 'select',
      options: [
        { label: '5m', value: '5m' },
        { label: '15m', value: '15m' },
      ],
    },
    {
      key: 'sideMode',
      label: 'Side',
      input: 'select',
      options: [
        { label: 'all', value: 'all' },
        { label: 'up', value: 'up' },
        { label: 'down', value: 'down' },
      ],
    },
    {
      key: 'baseSizing',
      label: 'Base Sizing',
      input: 'select',
      options: [
        { label: 'shares', value: 'shares' },
        { label: 'usdc', value: 'usdc' },
      ],
    },
    { key: 'baseShares', label: 'Base Shares', input: 'number' },
    { key: 'baseUsdc', label: 'Base USDC', input: 'number' },
    {
      key: 'basePriceUsdc',
      label: 'Base Price (USDC)',
      input: 'number',
      help: '0.55 gibi bir deger girersen ilk alim da bu fiyata gelince tetiklenir. Bos birakirsan ilk alim aninda calisir.',
    },
    { key: 'dcaLevels', label: 'DCA Levels (Base Haric)', input: 'number' },
    { key: 'nearStep', label: 'Near Step', input: 'number' },
    { key: 'stepMult', label: 'Step Mult.', input: 'number' },
    { key: 'sizeMult', label: 'Size Mult.', input: 'number' },
    { key: 'minPriceDistanceCent', label: 'Min Price Distance (cent)', input: 'number' },
    { key: 'cutoffMin', label: 'Cutoff Min', input: 'number' },
    { key: 'tpProfitPct', label: 'TP Profit (USDC)', input: 'number' },
    { key: 'slLossPct', label: 'SL Loss (USDC)', input: 'number' },
    { key: 'slSpreadPct', label: 'SL Spread (USDC)', input: 'number' },
    { key: 'refKey', label: 'Reference Key', input: 'text' },
  ],
  'action.place_order': [
    { key: 'sourceTradeId', label: 'Source Trade ID', input: 'number' },
    {
      key: 'side',
      label: 'Yön',
      input: 'select',
      options: [
        { label: 'buy', value: 'buy' },
        { label: 'sell', value: 'sell' },
      ],
    },
    {
      key: 'executionMode',
      label: 'Islem Modu',
      input: 'select',
      options: [
        { label: 'market (IOC)', value: 'market' },
        { label: 'limit (GTC)', value: 'limit' },
      ],
      help: 'market secimi piyasa benzeri davranis icin IOC + agresif fiyat kullanir.',
    },
    { key: 'marketSlug', label: 'Market Slug', input: 'text' },
    { key: 'tokenId', label: 'Token ID', input: 'text' },
    { key: 'outcomeLabel', label: 'Outcome Label', input: 'text' },
    {
      key: 'sizeMode',
      label: 'Tutar Modu',
      input: 'select',
      options: [
        { label: 'USDC', value: 'usdc' },
        { label: '% (Pozisyon Yüzdesi)', value: 'pct' },
      ],
      help: "pct seçersen tutar Source Trade notional'ının yüzdesi olarak hesaplanır.",
    },
    { key: 'sizeUsdc', label: 'Tutar (USDC)', input: 'number' },
    { key: 'sizePct', label: 'Tutar (%)', input: 'number', help: 'Geçerli aralık: 0 < % <= 100.' },
    { key: 'minPriceDistanceCent', label: 'Minimum Fiyat Mesafesi (cent)', input: 'number' },
    { key: 'maxTriggers', label: 'Maksimum Tetikleme', input: 'number' },
    {
      key: 'kind',
      label: 'Emir Tipi',
      input: 'select',
      options: [
        { label: 'immediate', value: 'immediate' },
        { label: 'conditional', value: 'conditional' },
      ],
    },
    {
      key: 'triggerCondition',
      label: 'Tetik Koşulu',
      input: 'select',
      options: [
        { label: 'Yok', value: '' },
        { label: 'cross_above', value: 'cross_above' },
        { label: 'cross_below', value: 'cross_below' },
        { label: 'level_above', value: 'level_above' },
        { label: 'level_below', value: 'level_below' },
      ],
    },
    { key: 'triggerPrice', label: 'Tetik Fiyatı', input: 'number', help: 'cross_* icin gecis seviyesi, level_* icin durum eşiği olarak kullanılır.' },
    { key: 'expiresAt', label: 'Bitiş Zamanı', input: 'datetime-local' },
    {
      key: 'tpEnabled',
      label: 'Take Profit',
      input: 'select',
      options: [
        { label: 'Kapali', value: 'false' },
        { label: 'Aktif', value: 'true' },
      ],
      help: 'Buy emri doldurulunca TP child sell acmaya izin verir. TP Fiyat alani hard full-close TP icin, kademe satirlari ise staged partial TP icin kullanilir; ikisi ayni anda aktif olabilir.',
    },
    { key: 'tpPriceCent', label: 'TP Fiyat (cent)', input: 'number', help: 'Hard full-close TP seviyesi. Tetiklenirse o andaki kalan pozisyonun tamami kapanir; staged TP satirlariyla birlikte kullanilabilir.' },
    {
      key: 'slEnabled',
      label: 'Stop Loss',
      input: 'select',
      options: [
        { label: 'Kapali', value: 'false' },
        { label: 'Aktif', value: 'true' },
      ],
      help: 'Buy emri doldurulunca SL child sell acmaya izin verir. SL Fiyat alani hard full-close SL icin, kademe satirlari ise staged partial SL icin kullanilir; ikisi ayni anda aktif olabilir.',
    },
    { key: 'slPriceCent', label: 'SL Fiyat (cent)', input: 'number', help: 'Hard full-close SL seviyesi. Tetiklenirse o andaki kalan pozisyonun tamami kapanir; staged SL satirlariyla birlikte kullanilabilir.' },
    {
      key: 'slTriggerPriceMode',
      label: 'SL Tetik Fiyat Modu',
      input: 'select',
      options: [
        { label: 'Best Bid', value: 'best_bid' },
        { label: 'Composite (Legacy)', value: 'composite' },
        { label: 'Composite Safe', value: 'composite_safe' },
        { label: 'Composite Fast', value: 'composite_fast' },
        { label: 'Last Trade', value: 'last_trade' },
      ],
      help: 'Best Bid: en konservatif. Composite (Legacy): mevcut eski composite davranisi. Composite Safe: divergence + best bid onayi ile daha gec tetikler. Composite Fast: min(best_bid,last_trade) ile daha hizli tetikler. Last Trade: sadece son islemi kullanir.',
    },
    {
      key: 'reenterOnSlHit',
      label: 'SL Sonrasi Re-entry',
      input: 'checkbox',
      help: 'Yalniz upstream trigger.market_price repeatMode=once arkasindaki immediate buy node icin gecerli. SL ladder aktifse tum SL kademeleri icin ortak re-entry davranisini kontrol eder.',
    },
    {
      key: 'reentryMaxAttempts',
      label: 'Re-entry Deneme Limiti',
      input: 'number',
      help: 'SL sonrasi maksimum yeniden alis deneme sayisi. Gecerli aralik: 1-10.',
    },
    {
      key: 'reentryMinPriceCent',
      label: 'Re-entry Min Fiyat (cent)',
      input: 'number',
      help: 'Yalniz re-entry denemelerinde uygulanir. Current price bu seviyenin altindaysa mevcut trigger guard semantigiyle bloklar.',
    },
    {
      key: 'reentryMaxPriceCent',
      label: 'Re-entry Max Fiyat (cent)',
      input: 'number',
      help: 'Yalniz re-entry denemelerinde uygulanir. Best ask / desired reference bu seviyeyi asarsa mevcut max price guard semantigiyle bloklar.',
    },
    {
      key: 'maxPriceCent',
      label: 'Tavan Fiyat (cent)',
      input: 'number',
      help: 'Bu fiyatin ustunde buy emri gonderme. Bossa node ici tavan snapshot yoktur; upstream tetik gecerli bir maxPrice tasiyorsa editor onu otomatik doldurabilir.',
    },
    {
      key: 'triggerPriceGuardEnabled',
      label: 'Tetik Fiyat Korumasi',
      input: 'checkbox',
      help: 'Runtime current_price upstream tetik fiyatinin altina dusulurse buy emrini engelle.',
    },
    {
      key: 'retryOnTriggerPriceGuardBlock',
      label: 'Tetik Fiyat Bekle',
      input: 'checkbox',
      help: 'Trigger guard orderi iptal etmek yerine beklemeye alir; kosullar duzelince yeniden dener.',
    },
    {
      key: 'executionFloorGuardEnabled',
      label: 'Execution Floor Korumasi',
      input: 'checkbox',
      help: 'Best ask effective floor seviyesinin altindaysa buy emrini engelle. `Execution Floor Fiyat (cent)` bossa upstream tetik fiyati fallback olarak kullanilir.',
    },
    {
      key: 'executionFloorPriceCent',
      label: 'Execution Floor Fiyat (cent)',
      input: 'number',
      help: 'Opsiyonel floor override. Doluysa best ask bu seviyenin altina indiginde guard bloklar; bossa upstream tetik fiyati kullanilir.',
    },
    {
      key: 'retryOnExecutionFloorGuardBlock',
      label: 'Execution Floor Bekle',
      input: 'checkbox',
      help: 'Below-floor durumunda execution floor guard orderi iptal etmek yerine beklemeye alir; missing best ask mevcut runtime semantigini korur.',
    },
    {
      key: 'priceToBeatGuardEnabled',
      label: 'Price to Beat Korumasi',
      input: 'checkbox',
      help: 'Price to Beat ile ayni Polymarket/Chainlink current price feedini kullanir. Fark belirlenen minimum seviyenin altindaysa buy emrini engeller.',
    },
    {
      key: 'priceToBeatMaxDiff',
      label: 'Minimum Fark',
      input: 'number',
      help: 'Fark bu degerin altindaysa emir engellenir. USD secersen 5 = $5.00, cent secersen 1 = $0.01.',
    },
    {
      key: 'priceToBeatMaxDiffUnit',
      label: 'Fark Birimi',
      input: 'select',
      options: [
        { label: 'USD', value: 'usd' },
        { label: 'Cent', value: 'cent' },
      ],
      help: 'USD veya cent sec. Cent modu 0.01 gibi decimal cent degerleri de destekler.',
    },
    {
      key: 'notifyOnPriceToBeatGapBlocked',
      label: 'Price to Beat Engel Bildirimi',
      input: 'checkbox',
      help: 'Price to Beat guard emri engelleyince Telegram bildirimi gonder.',
    },
    {
      key: 'retryOnPriceToBeatGuardBlock',
      label: 'Price to Beat Bekle',
      input: 'checkbox',
      help: 'Price to Beat guard fail olursa node hata verip beklemeye alinır; kosullar duzelince tekrar dener.',
    },
    {
      key: 'notifyOnOrderPlaced',
      label: 'Emir Bildirimi (Telegram)',
      input: 'checkbox',
      help: 'Emir gercekten doldurulunca Telegram bildirimi gonder.',
    },
    {
      key: 'notifyOnOrderNotFilled',
      label: 'Expire/Error Bildirimi',
      input: 'checkbox',
      help: 'Emir hic fill olmadan expired veya terminal error durumuna duserse Telegram bildirimi gonder.',
    },
    {
      key: 'notifyOnTriggerPriceBlocked',
      label: 'Tetik Fiyat Engel Bildirimi',
      input: 'checkbox',
      help: 'Trigger price guard emri engelleyince bildirim gonder.',
    },
    {
      key: 'notifyOnExecutionFloorBlocked',
      label: 'Execution Floor Engel Bildirimi',
      input: 'checkbox',
      help: 'Execution floor guard emri engelleyince bildirim gonder.',
    },
    {
      key: 'notifyOnMaxPriceBlocked',
      label: 'Max Fiyat Engel Bildirimi',
      input: 'checkbox',
      help: 'Max price guard emri engelleyince bildirim gonder.',
    },
    {
      key: 'retryOnMaxPriceBlock',
      label: 'Max Fiyat Bekle',
      input: 'checkbox',
      help: 'Max price guard orderi iptal etmek yerine beklemeye alir; fiyat dusunce yeniden dener.',
    },
    {
      key: 'notifyOnTpHit',
      label: 'Take Profit Bildirimi',
      input: 'checkbox',
      help: 'TP child emri doldurulunca bildirim gonder.',
    },
    {
      key: 'notifyOnSlHit',
      label: 'Stop Loss Bildirimi',
      input: 'checkbox',
      help: 'SL child emri doldurulunca bildirim gonder.',
    },
    { key: 'refKey', label: 'Reference Key', input: 'text' },
  ],
  'action.cancel_order': [
    { key: 'builderOrderId', label: 'Builder Order ID', input: 'number' },
    { key: 'targetRef', label: 'Target Ref', input: 'text' },
  ],
  'action.update_order': [
    { key: 'builderOrderId', label: 'Builder Order ID', input: 'number' },
    { key: 'targetRef', label: 'Target Ref', input: 'text' },
    { key: 'minPriceDistanceCent', label: 'Minimum Fiyat Mesafesi (cent)', input: 'number' },
    { key: 'maxTriggers', label: 'Maksimum Tetikleme', input: 'number' },
  ],
  'action.set_state': [],
  'action.notify': [
    { key: 'channel', label: 'Kanal', input: 'text' },
    { key: 'message', label: 'Mesaj', input: 'textarea' },
  ],
  'action.telegram_notify': [
    {
      key: 'chatId',
      label: 'Chat ID (Opsiyonel Override)',
      input: 'text',
      placeholder: 'Bos birakirsan Settings -> Telegram chat_id kullanilir',
    },
    { key: 'message', label: 'Mesaj', input: 'textarea', placeholder: 'Tetik: {{vars.trigger_1_price}}' },
  ],
};
