import type { NodeFieldSchema } from './types';

export const NODE_FIELD_SCHEMAS: Record<string, NodeFieldSchema[]> = {
  'trigger.market_price': [
    {
      key: 'marketMode',
      label: 'Market Modu',
      input: 'select',
      options: [
        { label: 'Sabit (fixed)', value: 'fixed' },
        { label: 'Otomatik Scope (auto_scope)', value: 'auto_scope' },
      ],
    },
    { key: 'marketSlug', label: 'Market Slug', input: 'text' },
    {
      key: 'marketScope',
      label: 'Market Scope',
      input: 'select',
      options: [
        { label: 'BTC 5m', value: 'btc_5m_updown' },
        { label: 'BTC 15m', value: 'btc_15m_updown' },
        { label: 'ETH 5m', value: 'eth_5m_updown' },
        { label: 'ETH 15m', value: 'eth_15m_updown' },
        { label: 'SOL 5m', value: 'sol_5m_updown' },
        { label: 'SOL 15m', value: 'sol_15m_updown' },
        { label: 'XRP 5m', value: 'xrp_5m_updown' },
        { label: 'XRP 15m', value: 'xrp_15m_updown' },
      ],
    },
    {
      key: 'marketSelection',
      label: 'Secim Stratejisi',
      input: 'select',
      options: [{ label: 'latest_by_slug', value: 'latest_by_slug' }],
    },
    {
      key: 'protectionMode',
      label: 'Underlying Koruma',
      input: 'select',
      options: [
        { label: 'Kapali (off)', value: 'off' },
        { label: 'Asset teyidi', value: 'underlying_confirm' },
      ],
      help: 'Koruma secilen auto_scope assetine otomatik baglanir. BTC scope BTC ile, XRP scope XRP ile dogrulanir.',
    },
    {
      key: 'protectionPreset',
      label: 'Koruma Preseti',
      input: 'select',
      options: [
        { label: 'Loose', value: 'loose' },
        { label: 'Balanced', value: 'balanced' },
        { label: 'Strict', value: 'strict' },
      ],
      help: 'Balanced varsayilandir. Ayrica manuel asset secimi yoktur; secilen scope kullanilir.',
    },
    {
      key: 'cycleWindowMode',
      label: 'Cycle Pencere Modu',
      input: 'select',
      options: [
        { label: 'Tamamı (kapalı)', value: 'off' },
        { label: 'İlk N saniye (first)', value: 'first' },
        { label: 'Son N saniye (last)', value: 'last' },
      ],
      help: 'Cycle icinde sadece belirli bir zaman penceresinde tetik degerlendirilir. Auto-scope + `last` modunda son pencereye girdiginde ilk gorulen uygun fiyat da tetikleyebilir; fixed markette gercek cross aranir.',
    },
    {
      key: 'cycleWindowSecs',
      label: 'Pencere Süresi (saniye)',
      input: 'number',
      help: 'Kac saniye boyunca tetik degerlendirilecek. Or: 5m cycle, last 60 -> son 60sn. Auto-scope + `last` modunda son pencereye in-zone giris kabul edilir; fixed markette pencere icinde gercek gecis aranir.',
    },
    {
      key: 'repeatMode',
      label: 'Tetik Modu',
      input: 'select',
      options: [
        { label: '1 Kere (once)', value: 'once' },
        { label: 'Döngü (loop)', value: 'loop' },
      ],
    },
    {
      key: 'onceScope',
      label: 'Once Scope',
      input: 'select',
      options: [
        { label: 'Run', value: 'run' },
        { label: 'Market', value: 'market' },
      ],
      help: '`run` ilk basarili tetikten sonra workflow run boyunca tekrar almaz. `market` her yeni auto_scope markette bir kez daha tetikleyebilir. Auto-scope + once varsayilani markettir.',
    },
    { key: 'minIntervalMs', label: 'Kontrol Aralığı (ms)', input: 'number', help: 'Varsayılan: 10000 (10sn). Minimum: 250ms.' },
    { key: 'confirmationMs', label: 'Onay Süresi (ms)', input: 'number', help: 'Cross sonrası fiyatın eşikte kalması gereken süre. Boş = onay kapalı, 0 = anında tetik.' },
    {
      key: 'priceMode',
      label: 'Fiyat Kaynağı',
      input: 'select',
      options: [
        { label: 'site display (Polymarket UI)', value: 'site_display' },
        { label: 'midpoint (önerilen)', value: 'midpoint' },
        { label: 'raw trade (fallbacklı)', value: 'raw' },
        { label: 'last trade (strict)', value: 'last_trade' },
        { label: 'best bid (satış için)', value: 'best_bid' },
        { label: 'best ask (alış için)', value: 'best_ask' },
      ],
      help: 'site_display: Polymarket UI fiyatı; spread 10c altındaysa midpoint, üstündeyse son işlem fiyatı. midpoint: best bid/ask ortalaması. raw: son işlem fiyatını kullanır, yoksa midpoint fallback yapar. last_trade: sadece son işlem fiyatı kullanır, fallback yapmaz. best_bid: en iyi alım fiyatı. best_ask: en iyi satım fiyatı.',
    },
  ],
  'trigger.sell_progress': [
    { key: 'sourceTradeId', label: 'Source Trade ID', input: 'number' },
    { key: 'minProgressPct', label: 'Minimum İlerleme (%)', input: 'number' },
    { key: 'varKey', label: 'Değişken Anahtarı', input: 'text', placeholder: 'sell_progress_pct' },
    { key: 'minIntervalMs', label: 'Minimum Interval (ms)', input: 'number' },
  ],
  'trigger.open_positions': [
    { key: 'sourceTradeId', label: 'Source Trade ID', input: 'number' },
    { key: 'marketSlug', label: 'Market Slug', input: 'text' },
    { key: 'tokenId', label: 'Token ID', input: 'text' },
    { key: 'outcomeLabel', label: 'Outcome Label', input: 'text' },
    {
      key: 'triggerCondition',
      label: 'Fiyat Tetik Koşulu',
      input: 'select',
      options: [
        { label: 'Yok', value: '' },
        { label: 'cross_above', value: 'cross_above' },
        { label: 'cross_below', value: 'cross_below' },
      ],
    },
    {
      key: 'triggerPriceCent',
      label: 'Fiyat Eşiği (cent)',
      input: 'number',
      help: 'Örn: 70 girersen 70c.',
    },
    {
      key: 'maxPriceCent',
      label: 'Tavan Fiyati (cent)',
      input: 'number',
      help: 'Opsiyonel. cross_above ile birlikte kullanirsan triggerPrice ile bu tavan arasina girildiginde tetik sayilir; tavanin ustu tetiklenmez.',
    },
    {
      key: 'minIntervalMs',
      label: 'Minimum Interval (ms)',
      input: 'number',
      help: 'Fiyat tetik koşulu aktifse kullanılmaz; websocket event tetikler.',
    },
  ],
  'trigger.position_drawdown': [
    { key: 'marketSlug', label: 'Market Slug', input: 'text' },
    { key: 'outcomeLabel', label: 'Outcome Label', input: 'text' },
    {
      key: 'entryPriceCent',
      label: 'Entry Fiyati (cent)',
      input: 'number',
      help: 'Pozisyona bakmadan drawdown hesabi bu entry fiyatina gore yapilir. Ornek: 80 => $0.80',
    },
    {
      key: 'combineMode',
      label: 'Kural Birlesimi',
      input: 'select',
      options: [
        { label: 'Otomatik', value: '' },
        { label: 'AND (hepsi)', value: 'and' },
        { label: 'OR (herhangi biri)', value: 'or' },
      ],
      help: 'Bos birakirsan: tek kural varsa tek kural, birden fazla kural varsa OR uygulanir.',
    },
    {
      key: 'minIntervalMs',
      label: 'Minimum Interval (ms)',
      input: 'number',
      help: 'Varsayilan 250ms. Minimum 250ms.',
    },
    { key: 'varPrefix', label: 'Degisken Prefix', input: 'text', placeholder: 'drawdown' },
  ],
  'trigger.time_window': [
    { key: 'startAt', label: 'Başlangıç Zamanı', input: 'datetime-local' },
    { key: 'endAt', label: 'Bitiş Zamanı', input: 'datetime-local' },
    { key: 'varKey', label: 'Değişken Anahtarı', input: 'text', placeholder: 'time_window_open' },
    { key: 'minIntervalMs', label: 'Minimum Interval (ms)', input: 'number' },
  ],
  'logic.if': [
    { key: 'comment', label: 'Açıklama', input: 'textarea' },
  ],
  'logic.switch': [
    { key: 'comment', label: 'Açıklama', input: 'textarea' },
  ],
  'logic.delay': [
    { key: 'delayMs', label: 'Gecikme (ms)', input: 'number' },
  ],
  'logic.retry': [
    { key: 'maxAttempts', label: 'Maksimum Deneme', input: 'number' },
  ],
  'action.resolve_market': [
    {
      key: 'asset',
      label: 'Asset',
      input: 'select',
      options: [
        { label: 'BTC', value: 'btc' },
        { label: 'ETH', value: 'eth' },
        { label: 'SOL', value: 'sol' },
        { label: 'XRP', value: 'xrp' },
      ],
    },
    {
      key: 'timeframe',
      label: 'Timeframe',
      input: 'select',
      options: [
        { label: '5m', value: '5m' },
        { label: '15m', value: '15m' },
      ],
      help: 'Market slug bu secime gore otomatik hesaplanir.',
    },
    {
      key: 'selection',
      label: 'Secim Stratejisi',
      input: 'select',
      options: [{ label: 'latest_by_slug', value: 'latest_by_slug' }],
    },
    {
      key: 'outcomeLabel',
      label: 'Outcome',
      input: 'select',
      options: [
        { label: 'yes', value: 'yes' },
        { label: 'no', value: 'no' },
      ],
      help: 'tokenId secimi bu outcome alanina gore yapilir.',
    },
    {
      key: 'failOnMissingMarket',
      label: 'Market Yoksa Hata',
      input: 'select',
      options: [
        { label: 'true', value: 'true' },
        { label: 'false', value: 'false' },
      ],
    },
    {
      key: 'requireYesNoTokens',
      label: 'YES/NO Token Zorunlu',
      input: 'select',
      options: [
        { label: 'true', value: 'true' },
        { label: 'false', value: 'false' },
      ],
    },
    {
      key: 'requireTokenId',
      label: 'Secilen Token Zorunlu',
      input: 'select',
      options: [
        { label: 'true', value: 'true' },
        { label: 'false', value: 'false' },
      ],
    },
    { key: 'varPrefix', label: 'Degisken Prefix', input: 'text', placeholder: 'resolved_market' },
  ],
  'action.dual_dca': [
    { key: 'sourceTradeId', label: 'Source Trade ID', input: 'number' },
    {
      key: 'asset',
      label: 'Coin',
      input: 'select',
      options: [
        { label: 'BTC', value: 'btc' },
        { label: 'ETH', value: 'eth' },
        { label: 'SOL', value: 'sol' },
        { label: 'XRP', value: 'xrp' },
      ],
    },
    {
      key: 'timeframe',
      label: 'Market Period',
      input: 'select',
      options: [
        { label: '5m', value: '5m' },
        { label: '15m', value: '15m' },
      ],
    },
    {
      key: 'sideMode',
      label: 'Side',
      input: 'select',
      options: [
        { label: 'all', value: 'all' },
        { label: 'up', value: 'up' },
        { label: 'down', value: 'down' },
      ],
    },
    {
      key: 'baseSizing',
      label: 'Base Sizing',
      input: 'select',
      options: [
        { label: 'shares', value: 'shares' },
        { label: 'usdc', value: 'usdc' },
      ],
    },
    { key: 'baseShares', label: 'Base Shares', input: 'number' },
    { key: 'baseUsdc', label: 'Base USDC', input: 'number' },
    {
      key: 'basePriceUsdc',
      label: 'Base Price (USDC)',
      input: 'number',
      help: '0.55 gibi bir deger girersen ilk alim da bu fiyata gelince tetiklenir. Bos birakirsan ilk alim aninda calisir.',
    },
    { key: 'dcaLevels', label: 'DCA Levels (Base Haric)', input: 'number' },
    { key: 'nearStep', label: 'Near Step', input: 'number' },
    { key: 'stepMult', label: 'Step Mult.', input: 'number' },
    { key: 'sizeMult', label: 'Size Mult.', input: 'number' },
    { key: 'minPriceDistanceCent', label: 'Min Price Distance (cent)', input: 'number' },
    { key: 'cutoffMin', label: 'Cutoff Min', input: 'number' },
    { key: 'tpProfitPct', label: 'TP Profit (USDC)', input: 'number' },
    { key: 'slLossPct', label: 'SL Loss (USDC)', input: 'number' },
    { key: 'slSpreadPct', label: 'SL Spread (USDC)', input: 'number' },
    { key: 'refKey', label: 'Reference Key', input: 'text' },
  ],
  'action.place_order': [
    { key: 'sourceTradeId', label: 'Source Trade ID', input: 'number' },
    {
      key: 'side',
      label: 'Yön',
      input: 'select',
      options: [
        { label: 'buy', value: 'buy' },
        { label: 'sell', value: 'sell' },
      ],
    },
    {
      key: 'executionMode',
      label: 'Islem Modu',
      input: 'select',
      options: [
        { label: 'market (IOC)', value: 'market' },
        { label: 'limit (GTC)', value: 'limit' },
      ],
      help: 'market secimi piyasa benzeri davranis icin IOC + agresif fiyat kullanir.',
    },
    { key: 'marketSlug', label: 'Market Slug', input: 'text' },
    { key: 'tokenId', label: 'Token ID', input: 'text' },
    { key: 'outcomeLabel', label: 'Outcome Label', input: 'text' },
    {
      key: 'sizeMode',
      label: 'Tutar Modu',
      input: 'select',
      options: [
        { label: 'USDC', value: 'usdc' },
        { label: '% (Pozisyon Yüzdesi)', value: 'pct' },
      ],
      help: "pct seçersen tutar Source Trade notional'ının yüzdesi olarak hesaplanır.",
    },
    { key: 'sizeUsdc', label: 'Tutar (USDC)', input: 'number' },
    { key: 'sizePct', label: 'Tutar (%)', input: 'number', help: 'Geçerli aralık: 0 < % <= 100.' },
    { key: 'minPriceDistanceCent', label: 'Minimum Fiyat Mesafesi (cent)', input: 'number' },
    { key: 'maxTriggers', label: 'Maksimum Tetikleme', input: 'number' },
    {
      key: 'kind',
      label: 'Emir Tipi',
      input: 'select',
      options: [
        { label: 'immediate', value: 'immediate' },
        { label: 'conditional', value: 'conditional' },
      ],
    },
    {
      key: 'triggerCondition',
      label: 'Tetik Koşulu',
      input: 'select',
      options: [
        { label: 'Yok', value: '' },
        { label: 'cross_above', value: 'cross_above' },
        { label: 'cross_below', value: 'cross_below' },
      ],
    },
    { key: 'triggerPrice', label: 'Tetik Fiyatı', input: 'number' },
    { key: 'expiresAt', label: 'Bitiş Zamanı', input: 'datetime-local' },
    {
      key: 'tpEnabled',
      label: 'Take Profit',
      input: 'select',
      options: [
        { label: 'Kapali', value: 'false' },
        { label: 'Aktif', value: 'true' },
      ],
      help: 'Buy emri doldurulunca belirtilen fiyatta otomatik IOC sell emri olusturur.',
    },
    { key: 'tpPriceCent', label: 'TP Fiyat (cent)', input: 'number', help: 'Hedef satis fiyati (1-99 cent). Fiyat bu seviyeyi gecince marketten IOC ile satilir.' },
    {
      key: 'slEnabled',
      label: 'Stop Loss',
      input: 'select',
      options: [
        { label: 'Kapali', value: 'false' },
        { label: 'Aktif', value: 'true' },
      ],
      help: 'Buy emri doldurulunca belirtilen stop seviyesinde otomatik IOC sell emri olusturur.',
    },
    { key: 'slPriceCent', label: 'SL Fiyat (cent)', input: 'number', help: 'Stop satis fiyati (1-99 cent). Fiyat bu seviyenin altina inince marketten IOC ile satilir.' },
    { key: 'refKey', label: 'Reference Key', input: 'text' },
  ],
  'action.cancel_order': [
    { key: 'builderOrderId', label: 'Builder Order ID', input: 'number' },
    { key: 'targetRef', label: 'Target Ref', input: 'text' },
  ],
  'action.update_order': [
    { key: 'builderOrderId', label: 'Builder Order ID', input: 'number' },
    { key: 'targetRef', label: 'Target Ref', input: 'text' },
    { key: 'minPriceDistanceCent', label: 'Minimum Fiyat Mesafesi (cent)', input: 'number' },
    { key: 'maxTriggers', label: 'Maksimum Tetikleme', input: 'number' },
  ],
  'action.set_state': [],
  'action.notify': [
    { key: 'channel', label: 'Kanal', input: 'text' },
    { key: 'message', label: 'Mesaj', input: 'textarea' },
  ],
  'action.telegram_notify': [
    {
      key: 'chatId',
      label: 'Chat ID (Opsiyonel Override)',
      input: 'text',
      placeholder: 'Bos birakirsan Settings -> Telegram chat_id kullanilir',
    },
    { key: 'message', label: 'Mesaj', input: 'textarea', placeholder: 'Tetik: {{vars.trigger_1_price}}' },
  ],
};
