ALTER TABLE trade_builder_orders
  ADD COLUMN IF NOT EXISTS notify_on_fill BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS notify_on_trigger_guard_blocked BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS notify_on_execution_floor_blocked BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS notify_on_tp_hit BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS notify_on_sl_hit BOOLEAN NOT NULL DEFAULT FALSE;
